In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

#import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import json
from pathlib import Path

In [4]:
data_path=Path("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json")
files=list(data_path.glob("*.json"))
len(files)

1095

In [5]:
file=open("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082591.json")
data=json.load(file)
len(data["innings"])

2

In [6]:
data["info"]

{'balls_per_over': 6,
 'city': 'Hyderabad',
 'dates': ['2017-04-05'],
 'event': {'match_number': 1, 'name': 'Indian Premier League'},
 'gender': 'male',
 'match_type': 'T20',
 'officials': {'match_referees': ['J Srinath'],
  'reserve_umpires': ['N Pandit'],
  'tv_umpires': ['A Deshmukh'],
  'umpires': ['AY Dandekar', 'NJ Llong']},
 'outcome': {'by': {'runs': 35}, 'winner': 'Sunrisers Hyderabad'},
 'overs': 20,
 'player_of_match': ['Yuvraj Singh'],
 'players': {'Royal Challengers Bangalore': ['CH Gayle',
   'Mandeep Singh',
   'TM Head',
   'KM Jadhav',
   'SR Watson',
   'Sachin Baby',
   'STR Binny',
   'S Aravind',
   'TS Mills',
   'YS Chahal',
   'A Choudhary'],
  'Sunrisers Hyderabad': ['DA Warner',
   'S Dhawan',
   'MC Henriques',
   'Yuvraj Singh',
   'DJ Hooda',
   'BCJ Cutting',
   'NV Ojha',
   'Bipul Sharma',
   'B Kumar',
   'A Nehra',
   'Rashid Khan']},
 'registry': {'people': {'A Choudhary': '18e6906e',
   'A Deshmukh': '6fda55cc',
   'A Nehra': '96fd40ae',
   'AY Dandekar': '2efc430e',
   'B Kumar': '2e81a32d',
   'BCJ Cutting': '2e11c706',
   'Bipul Sharma': 'c18496e1',
   'CH Gayle': 'db584dad',
   'CJ Jordan': 'ffe699c0',
   'DA Warner': 'dcce6f09',
   'DJ Hooda': '73ad96ed',
   'J Srinath': 'bad31fac',
   'KM Jadhav': '99d63244',
   'MC Henriques': '32198ae0',
   'Mandeep Singh': 'c3a96caf',
   'N Pandit': '4947c258',
   'NJ Llong': '573fb985',
   'NV Ojha': '890946a0',
   'Rashid Khan': '5f547c8b',
   'S Aravind': '957532de',
   'S Dhawan': '0a476045',
   'SR Watson': '4329fbb5',
   'STR Binny': 'bd17b45f',
   'Sachin Baby': 'dc9dd038',
   'TM Head': '12b610c2',
   'TS Mills': '245c97cb',
   'YS Chahal': '57ee1fde',
   'Yuvraj Singh': '1c914163'}},
 'season': 2017,
 'team_type': 'club',
 'teams': ['Sunrisers Hyderabad', 'Royal Challengers Bangalore'],
 'toss': {'decision': 'field', 'winner': 'Royal Challengers Bangalore'},
 'venue': 'Rajiv Gandhi International Stadium, Uppal'}

In [7]:
data["info"]["city"]

'Hyderabad'

### DLS

In [8]:
file=open("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370353.json")
data=json.load(file)
data["info"]

/tmp/ipykernel_33/3037241801.py:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082591.json' mode='r' encoding='UTF-8'>
  file=open("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370353.json")
ResourceWarning: Enable tracemalloc to get the object allocation traceback

{'balls_per_over': 6,
 'city': 'Ahmedabad',
 'dates': ['2023-05-29'],
 'event': {'name': 'Indian Premier League', 'stage': 'Final'},
 'gender': 'male',
 'match_type': 'T20',
 'officials': {'match_referees': ['J Srinath'],
  'reserve_umpires': ['J Madanagopal'],
  'tv_umpires': ['KN Ananthapadmanabhan'],
  'umpires': ['Nitin Menon', 'RJ Tucker']},
 'outcome': {'winner': 'Chennai Super Kings',
  'by': {'wickets': 5},
  'method': 'D/L'},
 'overs': 20,
 'player_of_match': ['DP Conway'],
 'players': {'Gujarat Titans': ['WP Saha',
   'Shubman Gill',
   'B Sai Sudharsan',
   'HH Pandya',
   'Rashid Khan',
   'V Shankar',
   'DA Miller',
   'R Tewatia',
   'MM Sharma',
   'Noor Ahmad',
   'Mohammed Shami',
   'J Little'],
  'Chennai Super Kings': ['RD Gaikwad',
   'DP Conway',
   'S Dube',
   'AM Rahane',
   'AT Rayudu',
   'MS Dhoni',
   'RA Jadeja',
   'MM Ali',
   'DL Chahar',
   'M Pathirana',
   'TU Deshpande',
   'M Theekshana']},
 'registry': {'people': {'AM Rahane': '29e95537',
   'AT Rayudu': '70d205c9',
   'B Sai Sudharsan': 'd5130a30',
   'DA Miller': 'd67d5f00',
   'DL Chahar': '23eeb873',
   'DP Conway': 'df5a6881',
   'HH Pandya': 'dbe50b21',
   'J Little': '9061a703',
   'J Madanagopal': '8275b04a',
   'J Srinath': 'bad31fac',
   'KN Ananthapadmanabhan': '3144063a',
   'M Pathirana': '64839cb3',
   'M Theekshana': 'f24c6701',
   'MM Ali': 'bb351c23',
   'MM Sharma': '759ac88f',
   'MS Dhoni': '4a8a2e3b',
   'Mohammed Shami': '8cf9814c',
   'Nitin Menon': 'e1d41d9e',
   'Noor Ahmad': 'efc04be7',
   'R Tewatia': '39a2dfa8',
   'RA Jadeja': 'fe93fd9d',
   'RD Gaikwad': '45a43fe2',
   'RJ Tucker': '38810cfc',
   'Rashid Khan': '5f547c8b',
   'S Dube': 'a4e37e47',
   'Shubman Gill': 'b4b99816',
   'TU Deshpande': '46a9bea1',
   'V Shankar': '0994d0ae',
   'WP Saha': 'fe11caa6'}},
 'season': '2023',
 'team_type': 'club',
 'teams': ['Gujarat Titans', 'Chennai Super Kings'],
 'toss': {'decision': 'field', 'winner': 'Chennai Super Kings'},
 'venue': 'Narendra Modi Stadium, Ahmedabad'}

### Ties and Super Overs

In [19]:
match_data=open("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216493.json")
match_data=json.load(match_data)
match_data["info"]["outcome"]

{'result': 'tie', 'eliminator': 'Delhi Capitals'}

In [27]:
len(match_data["innings"])

4

In [34]:
extract_info("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216493.json")

In [163]:
def extract_info(file_name): ##Removed DLS Matches and Super Over Matches
    file=open(file_name)
    data=json.load(file)
    info={}
    if "winner" not in data["info"]["outcome"]:
        return
    if "method" in data["info"]["outcome"] and data["info"]["outcome"]["method"]=="D/L":
        return
    info["Match_id"]=str(file_name).split("/")[-1][:-5]
    city_name=""
    if "city" in data["info"]:
        city_name=","+data["info"]["city"]
    info["Venue"]=data["info"]["venue"]+city_name
    info["Team1"]=data["info"]["teams"][0]
    info["Team2"]=data["info"]["teams"][1]
    info["Winner"]=data["info"]['outcome']["winner"]
    file.close()
    return info

In [164]:
extract_info("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598025.json")

{'Match_id': '598025',
 'Venue': 'Punjab Cricket Association Stadium, Mohali,Chandigarh',
 'Team1': 'Kings XI Punjab',
 'Team2': 'Pune Warriors',
 'Winner': 'Kings XI Punjab'}

In [165]:
df=pd.DataFrame(columns=["Match_id","Venue","Team1","Team2","Winner"])

In [166]:
match_info=[]
for i in range(len(files)):
    d=extract_info(files[i])
    if d:
        match_info.append(d)
        
len(match_info)

/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598004.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254077.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501255.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082625.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980989.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501245.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136592.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419121.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136578.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136566.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501265.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598017.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216547.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829741.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216512.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1175365.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829807.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336022.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392183.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829813.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829763.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729315.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082648.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980997.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216517.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501215.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359476.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/733993.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370353.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216493.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829743.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178426.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392190.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336025.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392186.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178424.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392214.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980999.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980943.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/tmp/ipykernel_33/4180533359.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359519.json' mode='r' encoding='UTF-8'>
  d=extract_info(files[i])
ResourceWarning: Enable tracemalloc to get the object allocation traceback

1055

In [167]:
df=pd.DataFrame.from_dict(match_info)
df

,Match_id,Venue,Team1,Team2,Winner
0,598025,"Punjab Cricket Association Stadium, Mohali,Cha...",Kings XI Punjab,Pune Warriors,Kings XI Punjab
1,1370352,"Narendra Modi Stadium, Ahmedabad,Ahmedabad",Gujarat Titans,Mumbai Indians,Gujarat Titans
2,1216499,"Sheikh Zayed Stadium,Abu Dhabi",Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians
3,1082608,"Feroz Shah Kotla,Delhi",Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders
4,1082612,"Holkar Cricket Stadium,Indore",Kings XI Punjab,Mumbai Indians,Mumbai Indians
...,...,...,...,...,...
1050,1304101,"Dr DY Patil Sports Academy, Mumbai,Navi Mumbai",Chennai Super Kings,Delhi Capitals,Chennai Super Kings
1051,419164,"Dr DY Patil Sports Academy,Mumbai",Royal Challengers Bangalore,Deccan Chargers,Royal Challengers Bangalore
1052,501206,"Punjab Cricket Association Stadium, Mohali,Cha...",Kings XI Punjab,Chennai Super Kings,Kings XI Punjab
1053,548319,"Punjab Cricket Association Stadium, Mohali,Cha...",Kings XI Punjab,Pune Warriors,Kings XI Punjab
1054,1178419,"MA Chidambaram Stadium,Chennai",Mumbai Indians,Chennai Super Kings,Mumbai Indians

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Match_id  1055 non-null   object
 1   Venue     1055 non-null   object
 2   Team1     1055 non-null   object
 3   Team2     1055 non-null   object
 4   Winner    1055 non-null   object
dtypes: object(5)
memory usage: 41.3+ KB

In [35]:
df.duplicated().sum()

0

In [169]:
def edit_venue(row):
    venues=["Dubai International Cricket Stadium","Sharjah Cricket Stadium"]
    if row["Venue"] in venues:
        row["Venue"]+=","+row["Venue"].split(" ")[0]
    return row["Venue"]
        
    
df["Venue"]=df.apply(edit_venue,axis=1)

In [170]:
def edit_venue(row):
    s=row["Venue"]
    ven=s.split(",")[1:]
    val=ven[0].strip()
    if val=="Chepauk":
        return "Chennai"
    elif val=="Uppal":
        return "Hyderabad"
    elif val=="Motera":
        return"Ahmedabad"
    elif val=="Jamtha":
        return "Nagpur"
    elif val=="Chandigarh":
        return "Mohali"
    else:
        return val

df["Venue"]=df.apply(edit_venue,axis=1)
for i in df["Venue"].unique():
    print(i)

Mohali
Ahmedabad
Abu Dhabi
Delhi
Indore
Chennai
Dubai
Kolkata
Pune
Mumbai
Hyderabad
Durban
Jaipur
Centurion
Bangalore
Port Elizabeth
Cape Town
Lucknow
Raipur
Johannesburg
Sharjah
Ranchi
Mullanpur
Kanpur
Nagpur
Cuttack
Rajkot
Dharamsala
Bengaluru
Guwahati
Visakhapatnam
Bloemfontein
Kochi
East London
Kimberley

In [171]:
df

,Match_id,Venue,Team1,Team2,Winner
0,598025,Mohali,Kings XI Punjab,Pune Warriors,Kings XI Punjab
1,1370352,Ahmedabad,Gujarat Titans,Mumbai Indians,Gujarat Titans
2,1216499,Abu Dhabi,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians
3,1082608,Delhi,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders
4,1082612,Indore,Kings XI Punjab,Mumbai Indians,Mumbai Indians
...,...,...,...,...,...
1050,1304101,Mumbai,Chennai Super Kings,Delhi Capitals,Chennai Super Kings
1051,419164,Mumbai,Royal Challengers Bangalore,Deccan Chargers,Royal Challengers Bangalore
1052,501206,Mohali,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab
1053,548319,Mohali,Kings XI Punjab,Pune Warriors,Kings XI Punjab
1054,1178419,Chennai,Mumbai Indians,Chennai Super Kings,Mumbai Indians

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Match_id  1055 non-null   object
 1   Venue     1055 non-null   object
 2   Team1     1055 non-null   object
 3   Team2     1055 non-null   object
 4   Winner    1055 non-null   object
dtypes: object(5)
memory usage: 41.3+ KB

In [174]:
df.to_csv("Matches.csv",index=False)

In [175]:
dr=pd.read_csv("/kaggle/working/Matches.csv")
dr.shape,dr.columns,dr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Match_id  1055 non-null   int64
 1   Venue     1055 non-null   object
 2   Team1     1055 non-null   object
 3   Team2     1055 non-null   object
 4   Winner    1055 non-null   object
dtypes: int64(1), object(4)
memory usage: 41.3+ KB

((1055, 5),
 Index(['Match_id', 'Venue', 'Team1', 'Team2', 'Winner'], dtype='object'),
 None)

### Match Data

In [59]:
file=open("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370352.json")
data=json.load(file)
data["innings"][1]["target"]["runs"],data["innings"][1]["team"]

(234, 'Mumbai Indians')

In [60]:
data["innings"][1]["overs"][1]

{'over': 1,
 'deliveries': [{'batter': 'RG Sharma',
   'bowler': 'HH Pandya',
   'non_striker': 'C Green',
   'runs': {'batter': 4, 'extras': 0, 'total': 4}},
  {'batter': 'RG Sharma',
   'bowler': 'HH Pandya',
   'non_striker': 'C Green',
   'runs': {'batter': 2, 'extras': 0, 'total': 2}},
  {'batter': 'RG Sharma',
   'bowler': 'HH Pandya',
   'non_striker': 'C Green',
   'runs': {'batter': 1, 'extras': 0, 'total': 1}},
  {'batter': 'C Green',
   'bowler': 'HH Pandya',
   'extras': {'wides': 1},
   'non_striker': 'RG Sharma',
   'runs': {'batter': 0, 'extras': 1, 'total': 1}},
  {'batter': 'C Green',
   'bowler': 'HH Pandya',
   'non_striker': 'RG Sharma',
   'runs': {'batter': 0, 'extras': 0, 'total': 0}},
  {'batter': 'C Green',
   'bowler': 'HH Pandya',
   'non_striker': 'RG Sharma',
   'runs': {'batter': 0, 'extras': 0, 'total': 0}},
  {'batter': 'SA Yadav',
   'bowler': 'HH Pandya',
   'non_striker': 'RG Sharma',
   'replacements': {'role': [{'in': 'SA Yadav',
      'out': 'C Green',
      'reason': 'injury',
      'role': 'batter'}]},
   'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}

In [61]:
type(pd.json_normalize(data["innings"][1]["overs"][0]["deliveries"]))

pandas.core.frame.DataFrame

In [62]:
len(data["innings"][1]["overs"])#[0]["deliveries"])

19

In [63]:
over=10
counter=[1,2,3,4,5,6]
idx=0
df=pd.json_normalize(data["innings"][1]["overs"][over]["deliveries"])
df["over"]=over
df["ball"]=-1
df["batting_team"]=data["innings"][1]["team"]
df["bowling_team"]=data["innings"][0]["team"]
df["target"]=data["innings"][1]["target"]["runs"]
if "wickets" not in df.columns:
    df["wickets"]=0
if "extras.noballs" not in df.columns:
    df["extras.noballs"]=0
if "extras.wides" not in df.columns:
    df["extras.wides"]=0
    
df["wickets"]=df["wickets"].fillna(0)
df["wickets"]=df["wickets"].apply(lambda x:x if x==0 else 1)

df["extras.noballs"]=df["extras.noballs"].fillna(0)
df["extras.noballs"]=df["extras.noballs"].apply(lambda x:x if x==0 else 1)

df["extras.wides"]=df["extras.wides"].fillna(0)
df["extras.wides"]=df["extras.wides"].apply(lambda x:x if x==0 else 1)

df=df.drop(columns=["runs.batter","runs.extras"])
for i in df.index:
    if df["extras.noballs"][i] or df["extras.wides"][i]:
        df.loc[i,"ball"]=counter[idx]
    else:
        df.loc[i,"ball"]=counter[idx]
        idx+=1

df=df[["batter","non_striker","batting_team","bowling_team","runs.total","over","ball","target","wickets"]]
df

,batter,non_striker,batting_team,bowling_team,runs.total,over,ball,target,wickets
0,SA Yadav,C Green,Mumbai Indians,Gujarat Titans,1,10,1,234,0
1,SA Yadav,C Green,Mumbai Indians,Gujarat Titans,1,10,1,234,0
2,C Green,SA Yadav,Mumbai Indians,Gujarat Titans,2,10,2,234,0
3,C Green,SA Yadav,Mumbai Indians,Gujarat Titans,0,10,3,234,0
4,C Green,SA Yadav,Mumbai Indians,Gujarat Titans,6,10,4,234,0
5,C Green,SA Yadav,Mumbai Indians,Gujarat Titans,2,10,5,234,0
6,SA Yadav,C Green,Mumbai Indians,Gujarat Titans,0,10,5,234,0
7,SA Yadav,C Green,Mumbai Indians,Gujarat Titans,1,10,6,234,0

In [64]:
file_name="/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082591.json"
file_name.split("/")[-1][:-5]

'1082591'

In [176]:
match_data=pd.read_csv("/kaggle/working/Matches.csv")
match_data["Match_id"]=match_data["Match_id"].astype(str)
match_data

,Match_id,Venue,Team1,Team2,Winner
0,598025,Mohali,Kings XI Punjab,Pune Warriors,Kings XI Punjab
1,1370352,Ahmedabad,Gujarat Titans,Mumbai Indians,Gujarat Titans
2,1216499,Abu Dhabi,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians
3,1082608,Delhi,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders
4,1082612,Indore,Kings XI Punjab,Mumbai Indians,Mumbai Indians
...,...,...,...,...,...
1050,1304101,Mumbai,Chennai Super Kings,Delhi Capitals,Chennai Super Kings
1051,419164,Mumbai,Royal Challengers Bangalore,Deccan Chargers,Royal Challengers Bangalore
1052,501206,Mohali,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab
1053,548319,Mohali,Kings XI Punjab,Pune Warriors,Kings XI Punjab
1054,1178419,Chennai,Mumbai Indians,Chennai Super Kings,Mumbai Indians

In [177]:
match_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Match_id  1055 non-null   object
 1   Venue     1055 non-null   object
 2   Team1     1055 non-null   object
 3   Team2     1055 non-null   object
 4   Winner    1055 non-null   object
dtypes: object(5)
memory usage: 41.3+ KB

In [242]:
def extract_match_data(file_name):
    file=open(file_name)
    data=json.load(file)
    match_data=pd.read_csv("/kaggle/input/ipl-data-processed/Matches.csv")
    match_data["Match_id"]=match_data["Match_id"].astype(str)
    match_id=file_name.split("/")[-1][:-5]
    if match_id in ["1136564","335994","392198"]:
        file.close()
        return
    final_df=pd.DataFrame(columns=["Match_id","batter","non_striker","batting_team","bowling_team","over","ball","target","wickets"])
    for i in range(len(data["innings"][1]["overs"])):
        over=i
        counter=[1,2,3,4,5,6]
        idx=0
        df=pd.json_normalize(data["innings"][1]["overs"][over]["deliveries"])
        df["Match_id"]=match_id
        df["over"]=over
        df["ball"]=-1
        df["batting_team"]=data["innings"][1]["team"]
        df["bowling_team"]=data["innings"][0]["team"]
        df["target"]=data["innings"][1]["target"]["runs"]
        if "wickets" not in df.columns:
            df["wickets"]=0
        if "extras.noballs" not in df.columns:
            df["extras.noballs"]=0
        if "extras.wides" not in df.columns:
            df["extras.wides"]=0

        df["wickets"]=df["wickets"].fillna(0)
        df["wickets"]=df["wickets"].apply(lambda x:x if x==0 else 1)

        df["extras.noballs"]=df["extras.noballs"].fillna(0)
        df["extras.noballs"]=df["extras.noballs"].apply(lambda x:x if x==0 else 1)

        df["extras.wides"]=df["extras.wides"].fillna(0)
        df["extras.wides"]=df["extras.wides"].apply(lambda x:x if x==0 else 1)

        df=df.drop(columns=["runs.batter","runs.extras"])
        for i in df.index:
            if df["extras.noballs"][i] or df["extras.wides"][i]:
                df.loc[i,"ball"]=counter[idx]
            else:
                df.loc[i,"ball"]=counter[idx]
                idx+=1
        
        idx=0
        df=df[["Match_id","batter","non_striker","batting_team","bowling_team","over","ball","runs.total","target","wickets"]]
        df["runs_scored"]=df["runs.total"]
        df=df.drop(columns=["runs.total"])
        final_df=pd.concat([final_df,df],ignore_index=True)
    
    final_df["balls_bowled"]=final_df["over"]*6+final_df["ball"]
    final_df["balls_left"]=120-final_df["balls_bowled"]
    
    final_df["wickets"]=final_df["wickets"].cumsum()
    final_df["wickets_left"]=10-final_df["wickets"]
    
    final_df["runs_scored"]=final_df["runs_scored"].astype(int)
    final_df["total_runs"]=final_df["runs_scored"].cumsum()
    final_df["runs_left"]=final_df["target"]-final_df["total_runs"]
    final_df.loc[final_df["runs_left"]<0,"runs_left"]=0
    
    final_df["crr"]=final_df["total_runs"]*6/final_df["balls_bowled"]
    final_df["rrr"]=final_df["runs_left"]*6/(final_df["balls_left"]+10**(-2))
    
    final_df=final_df.drop(columns=["over","ball","balls_bowled"])
    final_df=final_df.drop(columns=["runs_scored","total_runs"])
    final_df=final_df.drop(columns=["wickets"])
    
    final_df=pd.merge(final_df,match_data[["Match_id","Venue","Winner"]],on="Match_id")
    final_df.loc[final_df["batting_team"]==final_df["Winner"],"Winner"]=1
    final_df.loc[final_df["bowling_team"]==final_df["Winner"],"Winner"]=0
    file.close()
    
    return final_df

In [243]:
df=extract_match_data("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082593.json")
df

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner
0,1082593,G Gambhir,CA Lynn,Kolkata Knight Riders,Gujarat Lions,184,119,10,183,6.0,9.226115,Rajkot,1
1,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,118,10,183,3.0,9.304296,Rajkot,1
2,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,117,10,182,4.0,9.332536,Rajkot,1
3,1082593,G Gambhir,CA Lynn,Kolkata Knight Riders,Gujarat Lions,184,116,10,182,3.0,9.412982,Rajkot,1
4,1082593,G Gambhir,CA Lynn,Kolkata Knight Riders,Gujarat Lions,184,115,10,181,3.6,9.442657,Rajkot,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,34,10,11,12.069767,1.940606,Rajkot,1
92,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,33,10,5,12.344828,0.908816,Rajkot,1
93,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,32,10,4,12.272727,0.749766,Rajkot,1
94,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,32,10,2,12.409091,0.374883,Rajkot,1
95,1082593,CA Lynn,G Gambhir,Kolkata Knight Riders,Gujarat Lions,184,31,10,0,12.404494,0.0,Rajkot,1

In [244]:
df2=extract_match_data("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370352.json")
df2

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner
0,1370352,RG Sharma,N Wadhera,Mumbai Indians,Gujarat Titans,234,119,10,234,0.0,11.797328,Ahmedabad,0
1,1370352,RG Sharma,N Wadhera,Mumbai Indians,Gujarat Titans,234,118,10,233,3.0,11.846454,Ahmedabad,0
2,1370352,N Wadhera,RG Sharma,Mumbai Indians,Gujarat Titans,234,117,10,233,2.0,11.947697,Ahmedabad,0
3,1370352,N Wadhera,RG Sharma,Mumbai Indians,Gujarat Titans,234,116,10,229,7.5,11.843807,Ahmedabad,0
4,1370352,N Wadhera,RG Sharma,Mumbai Indians,Gujarat Titans,234,115,9,229,6.0,11.946787,Ahmedabad,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,1370352,JP Behrendorff,K Kartikeya,Mumbai Indians,Gujarat Titans,234,14,1,68,9.396226,29.122056,Ahmedabad,0
111,1370352,K Kartikeya,JP Behrendorff,Mumbai Indians,Gujarat Titans,234,13,1,64,9.53271,29.515757,Ahmedabad,0
112,1370352,K Kartikeya,JP Behrendorff,Mumbai Indians,Gujarat Titans,234,12,1,64,9.444444,31.973356,Ahmedabad,0
113,1370352,JP Behrendorff,K Kartikeya,Mumbai Indians,Gujarat Titans,234,11,1,63,9.412844,34.332425,Ahmedabad,0
114,1370352,K Kartikeya,JP Behrendorff,Mumbai Indians,Gujarat Titans,234,10,0,63,9.327273,37.762238,Ahmedabad,0

In [245]:
df3=extract_match_data("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082596.json")
df3

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner
0,1082596,DA Warner,S Dhawan,Sunrisers Hyderabad,Gujarat Lions,136,119,10,136,0.0,6.856567,Hyderabad,1
1,1082596,DA Warner,S Dhawan,Sunrisers Hyderabad,Gujarat Lions,136,118,10,135,3.0,6.863825,Hyderabad,1
2,1082596,S Dhawan,DA Warner,Sunrisers Hyderabad,Gujarat Lions,136,117,10,134,4.0,6.871208,Hyderabad,1
3,1082596,DA Warner,S Dhawan,Sunrisers Hyderabad,Gujarat Lions,136,116,10,133,4.5,6.878717,Hyderabad,1
4,1082596,S Dhawan,DA Warner,Sunrisers Hyderabad,Gujarat Lions,136,115,10,133,3.6,6.938527,Hyderabad,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,1082596,MC Henriques,DA Warner,Sunrisers Hyderabad,Gujarat Lions,136,31,9,6,8.764045,1.160916,Hyderabad,1
92,1082596,MC Henriques,DA Warner,Sunrisers Hyderabad,Gujarat Lions,136,30,9,5,8.733333,0.999667,Hyderabad,1
93,1082596,MC Henriques,DA Warner,Sunrisers Hyderabad,Gujarat Lions,136,29,9,3,8.769231,0.620476,Hyderabad,1
94,1082596,MC Henriques,DA Warner,Sunrisers Hyderabad,Gujarat Lions,136,28,9,2,8.73913,0.428418,Hyderabad,1
95,1082596,DA Warner,MC Henriques,Sunrisers Hyderabad,Gujarat Lions,136,27,9,0,9.032258,0.0,Hyderabad,1

In [248]:
df3=extract_match_data("/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254058.json")
df3

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner
0,1254058,Washington Sundar,V Kohli,Royal Challengers Bangalore,Mumbai Indians,160,119,10,160,0.0,8.066549,Chennai,1
1,1254058,Washington Sundar,V Kohli,Royal Challengers Bangalore,Mumbai Indians,160,118,10,160,0.0,8.134904,Chennai,1
2,1254058,Washington Sundar,V Kohli,Royal Challengers Bangalore,Mumbai Indians,160,117,10,155,10.0,7.948039,Chennai,1
3,1254058,Washington Sundar,V Kohli,Royal Challengers Bangalore,Mumbai Indians,160,117,10,155,10.0,7.948039,Chennai,1
4,1254058,Washington Sundar,V Kohli,Royal Challengers Bangalore,Mumbai Indians,160,116,10,154,9.0,7.964831,Chennai,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,1254058,HV Patel,AB de Villiers,Royal Challengers Bangalore,Mumbai Indians,160,4,3,4,8.068966,5.985037,Chennai,1
122,1254058,HV Patel,AB de Villiers,Royal Challengers Bangalore,Mumbai Indians,160,3,3,3,8.051282,5.980066,Chennai,1
123,1254058,AB de Villiers,HV Patel,Royal Challengers Bangalore,Mumbai Indians,160,2,2,2,8.033898,5.970149,Chennai,1
124,1254058,Mohammed Siraj,HV Patel,Royal Challengers Bangalore,Mumbai Indians,160,1,2,1,8.016807,5.940594,Chennai,1
125,1254058,HV Patel,Mohammed Siraj,Royal Challengers Bangalore,Mumbai Indians,160,0,2,0,8.0,0.0,Chennai,1

In [238]:
df.columns

Index(['Match_id', 'batter', 'non_striker', 'batting_team', 'bowling_team',
       'target', 'balls_left', 'wickets_left', 'runs_left', 'crr', 'rrr',
       'Venue', 'Winner'],
      dtype='object')

In [247]:
deliveries=pd.DataFrame(columns=['Match_id', 'batter', 'non_striker', 'batting_team', 'bowling_team',
       'target', 'balls_left', 'wickets_left', 'runs_left', 'crr', 'rrr',
       'Venue', 'Winner'])

In [240]:
valid_matches=pd.read_csv("/kaggle/working/Matches.csv")
valid_matches["Match_id"].shape

(1055,)

In [249]:
for i in valid_matches["Match_id"]:
    file_path="/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/"+str(i)+".json"
    print(file_path)
    d=extract_match_data(file_path)
    if d is not None:
        deliveries=pd.concat([deliveries,d])

/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598025.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370352.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216499.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082608.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082612.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254058.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729303.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419139.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336020.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082620.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980945.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729287.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419125.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829761.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548372.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136564.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419113.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1237178.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392225.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734039.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729317.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178420.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548343.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304098.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136604.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392237.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082636.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178404.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216537.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359523.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598008.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392185.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980925.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501241.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082615.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/733983.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254103.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254085.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426305.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082631.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359496.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216510.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336017.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359475.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829759.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216501.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392231.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392181.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359513.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216494.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392212.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501218.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501203.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980949.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419150.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734025.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980995.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392222.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426282.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359481.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359487.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829753.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254068.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304113.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501237.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136610.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422139.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254099.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216529.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598035.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1175369.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254078.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392201.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598045.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980915.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/981011.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1237177.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392213.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336024.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392229.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392188.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419146.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136609.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254107.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426263.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/733979.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359503.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598061.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426275.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216498.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136586.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829717.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422119.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426278.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598044.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/981007.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422132.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734033.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419161.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254114.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426312.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136607.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980981.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216518.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336019.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254095.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/733991.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419147.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082622.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335994.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501251.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829783.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136561.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359516.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829745.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304067.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304058.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178415.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254083.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254093.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082607.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216520.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254089.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304052.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254108.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501224.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829747.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359501.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829709.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548330.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548335.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392219.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082613.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422127.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304114.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548348.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136588.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359507.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392207.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254060.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501252.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598015.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829817.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304054.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082604.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254084.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734005.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1175358.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254079.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178425.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548367.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304088.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254088.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419131.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501211.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359536.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216531.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/733977.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082603.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254098.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729307.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829711.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426287.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548361.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336040.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178409.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136575.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082641.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598038.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548378.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426286.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304094.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359542.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734037.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178394.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426307.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980927.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335985.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216530.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136570.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254063.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304111.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/981001.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598009.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501235.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216519.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501260.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734007.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422121.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419115.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729295.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335999.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/733997.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/981017.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426268.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304093.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082592.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598065.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335983.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829775.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082598.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178403.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1370350.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304086.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598058.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336013.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304081.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304104.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598068.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548371.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216505.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359527.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178429.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501219.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829799.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426264.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216502.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335995.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734027.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426283.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598001.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426310.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548329.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829769.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/597998.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548355.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598055.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829803.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501232.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082642.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548324.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254104.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216522.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359485.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598024.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1312199.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501199.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548357.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178422.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392238.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501234.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178427.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216508.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419138.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392234.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501267.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501247.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304108.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/980957.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548341.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426277.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392208.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426280.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598036.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1312197.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548381.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359492.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/597999.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136612.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359490.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254097.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136613.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1426288.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304089.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359506.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734035.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178399.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/729279.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734041.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422120.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216496.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304075.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734043.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359489.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136576.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548321.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304102.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392194.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829727.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/501263.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136597.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1178396.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254112.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422134.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304072.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136617.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1175362.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392184.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082601.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335997.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136568.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1136596.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216543.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304065.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422123.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392200.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304084.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419154.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082609.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598016.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/335986.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/419151.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1254111.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/734049.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1304051.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/392230.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359524.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1422137.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1216516.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829723.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548308.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1359498.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082646.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/829771.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598005.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/548354.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/336038.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/598019.json
/kaggle/input/ipl-all-time-data/IPL Data/ipl_json/1082649.json

In [2]:
deliveries=pd.read_csv("/kaggle/input/ipl-data-processed/Deliveries.csv")

In [3]:
deliveries.columns

Index(['Unnamed: 0', 'Match_id', 'batter', 'non_striker', 'batting_team',
       'bowling_team', 'target', 'balls_left', 'wickets_left', 'runs_left',
       'crr', 'rrr', 'Venue', 'Winner'],
      dtype='object')

In [4]:
deliveries=deliveries.drop(columns=["Unnamed: 0"])
deliveries

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner
0,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1
1,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1
2,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1
3,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1
4,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122322,1178419,MJ Santner,Harbhajan Singh,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0
122323,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0
122324,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0
122325,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0
122326,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0

In [20]:
deliveries.to_csv("Deliveries.csv",index=False)

In [18]:
strike_rates=pd.DataFrame(columns=["Batsman","Strike Rate"])

In [19]:
strike_rates["Batsman"]=pd.concat([deliveries["batter"],deliveries["non_striker"]]).unique()
strike_rates

           Batsman Strike Rate
0     AC Gilchrist         NaN
1    Azhar Mahmood         NaN
2          M Vohra         NaN
3    Mandeep Singh         NaN
4        DA Miller         NaN
..             ...         ...
613   P Ray Barman         NaN
614   BE Hendricks         NaN
615   TP Sudhindra         NaN
616    C Ganapathy         NaN
617  DJ Muthuswami         NaN

[618 rows x 2 columns]

In [28]:
df=pd.read_csv("/kaggle/input/ipl-all-time-data/IPL Data/Cricketers.csv")
df=df[["name","key_cricinfo"]]
df=df.dropna()
df["key_cricinfo"]=df["key_cricinfo"].astype(int)
df

                     name  key_cricinfo
0           AAA Amsterdam        772407
1               AA Adeoye        380588
2              AA Alleyne        661441
3               AAA Patel       1163136
4               AAA White        474307
...                   ...           ...
15188          Zulqarnain         43707
15189   Zulqarnain Haider         43860
15190   Zulqarnain Haider       1046641
15191  Zulufat Mutoniwase       1380564
15192         Zumika Azmi       1050037

[15148 rows x 2 columns]

In [36]:
df=df.rename(columns={"name":"Batsman"})
df

                  Batsman  key_cricinfo
0           AAA Amsterdam        772407
1               AA Adeoye        380588
2              AA Alleyne        661441
3               AAA Patel       1163136
4               AAA White        474307
...                   ...           ...
15188          Zulqarnain         43707
15189   Zulqarnain Haider         43860
15190   Zulqarnain Haider       1046641
15191  Zulufat Mutoniwase       1380564
15192         Zumika Azmi       1050037

[15148 rows x 2 columns]

In [37]:
df.columns

Index(['Batsman', 'key_cricinfo'], dtype='object')

In [38]:
strike_rates=pd.merge(strike_rates,df,on="Batsman")
strike_rates

           Batsman Strike Rate  key_cricinfo
0     AC Gilchrist         NaN          5390
1    Azhar Mahmood         NaN         39024
2          M Vohra         NaN        532856
3    Mandeep Singh         NaN        398506
4        DA Miller         NaN        321777
..             ...         ...           ...
641   P Ray Barman         NaN       1159712
642   BE Hendricks         NaN        379927
643   TP Sudhindra         NaN         34139
644    C Ganapathy         NaN         28764
645  DJ Muthuswami         NaN        528985

[646 rows x 3 columns]

In [42]:
strike_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646 entries, 0 to 645
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Batsman       646 non-null    object
 1   Strike Rate   0 non-null      object
 2   key_cricinfo  646 non-null    int64
dtypes: int64(1), object(2)
memory usage: 15.3+ KB

In [44]:
s=df.loc[df["Batsman"]=="AC Gilchrist"]["key_cricinfo"].item()
s

5390

In [ ]:
df[df["Batsman"]=="AC Gilchrist"]

### Trash Experiments

In [30]:
data["innings"][0]["team"],data["innings"][0]["overs"][0]

('Sunrisers Hyderabad',
 {'over': 0,
  'deliveries': [{'batter': 'DA Warner',
    'bowler': 'TS Mills',
    'non_striker': 'S Dhawan',
    'runs': {'batter': 0, 'extras': 0, 'total': 0}},
   {'batter': 'DA Warner',
    'bowler': 'TS Mills',
    'non_striker': 'S Dhawan',
    'runs': {'batter': 0, 'extras': 0, 'total': 0}},
   {'batter': 'DA Warner',
    'bowler': 'TS Mills',
    'non_striker': 'S Dhawan',
    'runs': {'batter': 4, 'extras': 0, 'total': 4}},
   {'batter': 'DA Warner',
    'bowler': 'TS Mills',
    'non_striker': 'S Dhawan',
    'runs': {'batter': 0, 'extras': 0, 'total': 0}},
   {'batter': 'DA Warner',
    'bowler': 'TS Mills',
    'extras': {'wides': 2},
    'non_striker': 'S Dhawan',
    'runs': {'batter': 0, 'extras': 2, 'total': 2}},
   {'batter': 'S Dhawan',
    'bowler': 'TS Mills',
    'non_striker': 'DA Warner',
    'runs': {'batter': 0, 'extras': 0, 'total': 0}},
   {'batter': 'S Dhawan',
    'bowler': 'TS Mills',
    'extras': {'legbyes': 1},
    'non_striker': 'DA Warner',
    'runs': {'batter': 0, 'extras': 1, 'total': 1}}]})

In [6]:
df=pd.json_normalize(data["innings"][0]["overs"][1]["deliveries"])
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets
0,S Dhawan,A Choudhary,DA Warner,1,0,1,NaN,NaN
1,DA Warner,A Choudhary,S Dhawan,4,0,4,NaN,NaN
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,NaN
3,DA Warner,A Choudhary,S Dhawan,6,0,6,NaN,NaN
4,DA Warner,A Choudhary,S Dhawan,0,0,0,NaN,"[{'kind': 'caught', 'player_out': 'DA Warner',..."
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,NaN,NaN
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,NaN,NaN

In [14]:
df["extras.wides"]=0
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over,ball
0,S Dhawan,A Choudhary,DA Warner,1,0,1,0.0,0,0,1,NaN
1,DA Warner,A Choudhary,S Dhawan,4,0,4,0.0,0,0,1,NaN
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,0,0,1,NaN
3,DA Warner,A Choudhary,S Dhawan,6,0,6,0.0,0,0,1,NaN
4,DA Warner,A Choudhary,S Dhawan,0,0,0,0.0,1,0,1,NaN
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,0.0,0,0,1,NaN
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,0.0,0,0,1,NaN

In [8]:
df["over"]=1
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over
0,S Dhawan,A Choudhary,DA Warner,1,0,1,NaN,NaN,NaN,1
1,DA Warner,A Choudhary,S Dhawan,4,0,4,NaN,NaN,NaN,1
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,NaN,NaN,1
3,DA Warner,A Choudhary,S Dhawan,6,0,6,NaN,NaN,NaN,1
4,DA Warner,A Choudhary,S Dhawan,0,0,0,NaN,"[{'kind': 'caught', 'player_out': 'DA Warner',...",NaN,1
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,NaN,NaN,NaN,1
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,NaN,NaN,NaN,1

In [9]:
df["wickets"]=df["wickets"].fillna(0)
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over
0,S Dhawan,A Choudhary,DA Warner,1,0,1,NaN,0,NaN,1
1,DA Warner,A Choudhary,S Dhawan,4,0,4,NaN,0,NaN,1
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,0,NaN,1
3,DA Warner,A Choudhary,S Dhawan,6,0,6,NaN,0,NaN,1
4,DA Warner,A Choudhary,S Dhawan,0,0,0,NaN,"[{'kind': 'caught', 'player_out': 'DA Warner',...",NaN,1
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,NaN,0,NaN,1
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,NaN,0,NaN,1

In [15]:
df["wickets"]=df["wickets"].apply(lambda x:x if x==0 else 1)
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over,ball
0,S Dhawan,A Choudhary,DA Warner,1,0,1,0.0,0,0,1,NaN
1,DA Warner,A Choudhary,S Dhawan,4,0,4,0.0,0,0,1,NaN
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,0,0,1,NaN
3,DA Warner,A Choudhary,S Dhawan,6,0,6,0.0,0,0,1,NaN
4,DA Warner,A Choudhary,S Dhawan,0,0,0,0.0,1,0,1,NaN
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,0.0,0,0,1,NaN
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,0.0,0,0,1,NaN

In [16]:
df["extras.noballs"]=df["extras.noballs"].fillna(0)
df["extras.wides"]=df["extras.wides"].fillna(0)
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over,ball
0,S Dhawan,A Choudhary,DA Warner,1,0,1,0.0,0,0,1,NaN
1,DA Warner,A Choudhary,S Dhawan,4,0,4,0.0,0,0,1,NaN
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,0,0,1,NaN
3,DA Warner,A Choudhary,S Dhawan,6,0,6,0.0,0,0,1,NaN
4,DA Warner,A Choudhary,S Dhawan,0,0,0,0.0,1,0,1,NaN
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,0.0,0,0,1,NaN
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,0.0,0,0,1,NaN

In [17]:
df["extras.noballs"]=df["extras.noballs"].astype(int)
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over,ball
0,S Dhawan,A Choudhary,DA Warner,1,0,1,0,0,0,1,NaN
1,DA Warner,A Choudhary,S Dhawan,4,0,4,0,0,0,1,NaN
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1,0,0,1,NaN
3,DA Warner,A Choudhary,S Dhawan,6,0,6,0,0,0,1,NaN
4,DA Warner,A Choudhary,S Dhawan,0,0,0,0,1,0,1,NaN
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,0,0,0,1,NaN
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,0,0,0,1,NaN

In [18]:
df["ball"]=0
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over,ball
0,S Dhawan,A Choudhary,DA Warner,1,0,1,0,0,0,1,0
1,DA Warner,A Choudhary,S Dhawan,4,0,4,0,0,0,1,0
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1,0,0,1,0
3,DA Warner,A Choudhary,S Dhawan,6,0,6,0,0,0,1,0
4,DA Warner,A Choudhary,S Dhawan,0,0,0,0,1,0,1,0
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,0,0,0,1,0
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,0,0,0,1,0

In [23]:
count=0
def ball_count(row):
    global count
    if row["extras.noballs"] or row["extras.wides"]:
        return count
    else:
        count+=1
        return count
    
df["ball"]=df.apply(ball_count,axis=1)
df

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,extras.wides,over,ball
0,S Dhawan,A Choudhary,DA Warner,1,0,1,0,0,0,1,1
1,DA Warner,A Choudhary,S Dhawan,4,0,4,0,0,0,1,2
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1,0,0,1,2
3,DA Warner,A Choudhary,S Dhawan,6,0,6,0,0,0,1,3
4,DA Warner,A Choudhary,S Dhawan,0,0,0,0,1,0,1,4
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,0,0,0,1,5
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,0,0,0,1,6

In [ ]:
df

In [24]:
df_final=pd.concat([df,df2])
df_final

,batter,bowler,non_striker,runs.batter,runs.extras,runs.total,extras.noballs,wickets,over,ball,extras.wides,extras.legbyes
0,S Dhawan,A Choudhary,DA Warner,1,0,1,NaN,NaN,1,1,NaN,NaN
1,DA Warner,A Choudhary,S Dhawan,4,0,4,NaN,NaN,1,2,NaN,NaN
2,DA Warner,A Choudhary,S Dhawan,0,1,1,1.0,NaN,1,3,NaN,NaN
3,DA Warner,A Choudhary,S Dhawan,6,0,6,NaN,NaN,1,4,NaN,NaN
4,DA Warner,A Choudhary,S Dhawan,0,0,0,NaN,"[{'kind': 'caught', 'player_out': 'DA Warner',...",1,5,NaN,NaN
5,MC Henriques,A Choudhary,S Dhawan,0,0,0,NaN,NaN,1,6,NaN,NaN
6,MC Henriques,A Choudhary,S Dhawan,4,0,4,NaN,NaN,1,7,NaN,NaN
0,DA Warner,TS Mills,S Dhawan,0,0,0,NaN,NaN,0,1,NaN,NaN
1,DA Warner,TS Mills,S Dhawan,0,0,0,NaN,NaN,0,2,NaN,NaN
2,DA Warner,TS Mills,S Dhawan,4,0,4,NaN,NaN,0,3,NaN,NaN
3,DA Warner,TS Mills,S Dhawan,0,0,0,NaN,NaN,0,4,NaN,NaN
4,DA Warner,TS Mills,S Dhawan,0,2,2,NaN,NaN,0,5,2.0,NaN
5,S Dhawan,TS Mills,DA Warner,0,0,0,NaN,NaN,0,6,NaN,NaN
6,S Dhawan,TS Mills,DA Warner,0,1,1,NaN,NaN,0,7,NaN,1.0

In [ ]:
def extract_match_data(file_name):

### Web Scraping For Strike Rates

In [19]:
import requests
from bs4 import BeautifulSoup
import dateparser

def get_career_averages(idt=277916,file_name=None, match_format=11, data_type='allround') :

        """Get Player career averages

        Arguements:
            file_name {string}: File name to save data
            match_format {int}: Match format (default is 11) (1-Test), (2-Odi) (3-T20I), (11-All International), (20-Youth Tests), (21-Youth ODI)
            data_type {string}: Data type (default is allround) (allround, batting, bowling, fielding)
        
        Return:
            Data in csv file
        """
        player_id=idt
        url = "https://www.espncricinfo.com/player/player-name-{0}".format(str(player_id))
        headers = {'user-agent': 'Mozilla/5.0'}
        match_format = match_format
        data_type = data_type
        #self.file_name = file_name

        #if self.file_name is None:
         #   self.file_name = f"{self.player_id}_{self.match_format}_{self.data_type}_career_averages.csv"

        url=f"https://stats.espncricinfo.com/ci/engine/player/{player_id}.html?class={match_format};template=results;type={data_type}"
        html_doc = requests.get(url, headers=headers)
        soup = BeautifulSoup(html_doc.text, 'html.parser')
        tables = soup.find_all("table")[2]
        table_rows = tables.find_all("tr")
        scores =[]
        for tr in table_rows:
            scores.append(tr.text)
            
        return scores,tables,table_rows

In [48]:
import requests
from bs4 import BeautifulSoup

In [179]:
import requests
from bs4 import BeautifulSoup

headers = {'user-agent': 'Mozilla/5.0'}
webpage=requests.get("https://stats.espncricinfo.com/ci/engine/player/34078.html",headers=headers).text
soup=BeautifulSoup(webpage,"lxml")

In [180]:
for i in soup.find_all("tr"):
    s=i.get_text("|",strip=True)
    print(s)

Format|Mat|Inns|NO|Runs|HS|Ave|BF|SR|100s|50s|4s|6s|Ct|St
ODIs|18|14|3|280|67|25.45|381|73.49|0|2|16|6|9|0
FC|69|104|9|3680|251*|38.73|-|-|6|19|-|-|22|0
List A|109|89|25|2922|125|45.65|-|-|4|23|-|-|39|0
T20s|14|10|1|45|12|5.00|55|81.81|0|0|3|0|5|0
Format|Mat|Inns|Balls|Runs|Wkts|BBI|BBM|Ave|Econ|SR|4w|5w|10w
ODIs|18|14|462|365|5|2/31|2/31|73.00|4.74|92.4|0|0|0
FC|69|-|6694|2991|102|5/30|-|29.32|2.68|65.6|-|3|0
List A|109|-|3259|2568|61|5/22|5/22|42.09|4.72|53.4|1|1|0
T20s|14|6|96|126|5|3/23|3/23|25.20|7.87|19.2|0|0|0
Format|Mat|Referee
FC|12|12
List A|11|11
T20s|9|9
Match|Bat|Bowl|Date|Ground|Format
Ninjas vs Avengers|22*|--|27-Mar-2023|Ghaziabad|OTHERT20
Ninjas vs Warriors|2|0/19|24-Mar-2023|Ghaziabad|OTHERT20
Ninjas vs Titans|1|0/29|23-Mar-2023|Ghaziabad|OTHERT20
Ninjas vs Knights|11|0/24|22-Mar-2023|Ghaziabad|OTHERT20
Maharajas vs Giants|2|--|15-Mar-2023|Doha|OTHERT20

In [181]:
for i in soup.find_all("p",class_="ds-text-title-subtle-s ds-font-medium ds-py-2 ds-ml-4 ds-text-typo ds-capitalize"):
    s=i.get_text("|",strip=True)
    print(s)

Batting & Fielding
Bowling
Umpire & Referee

In [187]:
for i in soup.find_all("tr"):
    s=i.get_text("|",strip=True)
    l=s.split("|")
    if l[0]=="T20s":
        if len(s)>=9:
            print(l[8])

81.81
25.20

In [182]:
values,results=[],[]
for i in soup.find_all("p",class_="ds-text-title-subtle-s ds-font-medium ds-py-2 ds-ml-4 ds-text-typo ds-capitalize"):
    s=i.get_text("|",strip=True)
    if s=="Batting & Fielding" or "Bowling":
        values.append(s)
    
for i in soup.find_all("tr"):
    s=i.get_text("|",strip=True)
    l=s.split("|")
    if l[0]=="T20s":
        results.append(l[8])
        
values,results
print(results[values.index("Batting & Fielding")])

IndexError: list index out of range

In [56]:
for i in soup.find_all("tr"):
    s=i.get_text("|",strip=True)
    l=s.split("|")
    if l[0]=="T20s":
        print(l[8])

169.82
25.05

In [188]:
def get_strike_rate(player_id):
    headers = {'user-agent': 'Mozilla/5.0'}
    url=f"https://stats.espncricinfo.com/ci/engine/player/{player_id}.html"
    webpage=requests.get(url,headers=headers).text 
    soup=BeautifulSoup(webpage,"lxml")
    values,results=[],[]
    for i in soup.find_all("p",class_="ds-text-title-subtle-s ds-font-medium ds-py-2 ds-ml-4 ds-text-typo ds-capitalize"):
        s=i.get_text("|",strip=True)
        values.append(s)

    for i in soup.find_all("tr"):
        s=i.get_text("|",strip=True)
        l=s.split("|")
        if l[0]=="T20s":
            if len(s)>=9:
                results.append(l[8])
            
    s=results[values.index("Batting & Fielding")]
    if s=="-":
        return "0"
    else:
        return s

In [64]:
get_strike_rate(df.loc[df["Batsman"]=="AC Gilchrist"]["key_cricinfo"].item())

'140.28'

In [67]:
get_strike_rate(1350792)

'0'

In [65]:
strike_rates

           Batsman Strike Rate  key_cricinfo
0     AC Gilchrist         NaN          5390
1    Azhar Mahmood         NaN         39024
2          M Vohra         NaN        532856
3    Mandeep Singh         NaN        398506
4        DA Miller         NaN        321777
..             ...         ...           ...
641   P Ray Barman         NaN       1159712
642   BE Hendricks         NaN        379927
643   TP Sudhindra         NaN         34139
644    C Ganapathy         NaN         28764
645  DJ Muthuswami         NaN        528985

[646 rows x 3 columns]

In [71]:
strike_rates["Batsman"].duplicated().sum()

28

In [74]:
strike_rates["Batsman"][strike_rates["Batsman"].duplicated()]

43           DR Smith
52       Yuvraj Singh
54      Shahid Afridi
60           RP Singh
114       CJ Anderson
161           SB Wagh
163          R Sharma
164          R Sharma
175       Abdul Samad
177       Rashid Khan
178       Rashid Khan
179       Rashid Khan
190          A Mishra
276          NK Patel
284            S Rana
289          MM Patel
382           J Botha
426    Jaskaran Singh
427    Jaskaran Singh
447       Sumit Kumar
460           A Singh
466     Mohammad Asif
467     Mohammad Asif
488     Harmeet Singh
493       Mohsin Khan
579       Arshad Khan
630       Kamran Khan
634          A Chopra
Name: Batsman, dtype: object

In [76]:
strike_rates[strike_rates["key_cricinfo"]==53910]

      Batsman Strike Rate  key_cricinfo
634  A Chopra         NaN         53910

In [78]:
strike_rates=strike_rates.drop(strike_rates[strike_rates["key_cricinfo"]==53910].index)

In [137]:
strike_rates["Batsman"][strike_rates["Batsman"].duplicated()]

Series([], Name: Batsman, dtype: object)

In [135]:
strike_rates[strike_rates["Batsman"]=="DR Smith"]

     Batsman Strike Rate  key_cricinfo
42  DR Smith         NaN         20236
43  DR Smith         NaN         53118

In [105]:
strike_rates=strike_rates.drop(strike_rates[(strike_rates["Batsman"]=="NK Patel")].index)

In [136]:
strike_rates=strike_rates.drop(strike_rates[(strike_rates["Batsman"]=="DR Smith") & (strike_rates["key_cricinfo"]!=53118)].index)

In [138]:
strike_rates.to_csv("Strike_Rates.csv",index=False)

In [139]:
strike_rates

           Batsman Strike Rate  key_cricinfo
0     AC Gilchrist         NaN          5390
1    Azhar Mahmood         NaN         39024
2          M Vohra         NaN        532856
3    Mandeep Singh         NaN        398506
4        DA Miller         NaN        321777
..             ...         ...           ...
641   P Ray Barman         NaN       1159712
642   BE Hendricks         NaN        379927
643   TP Sudhindra         NaN         34139
644    C Ganapathy         NaN         28764
645  DJ Muthuswami         NaN        528985

[615 rows x 3 columns]

In [160]:
prac_df=strike_rates
prac_df

           Batsman Strike Rate key_cricinfo
0     AC Gilchrist         NaN       140.28
1    Azhar Mahmood         NaN       135.32
2          M Vohra         NaN       128.27
3    Mandeep Singh         NaN       128.66
4        DA Miller         NaN       138.19
..             ...         ...          ...
641   P Ray Barman         NaN      1159712
642   BE Hendricks         NaN       379927
643   TP Sudhindra         NaN        34139
644    C Ganapathy         NaN        28764
645  DJ Muthuswami         NaN       528985

[615 rows x 3 columns]

In [150]:
d=prac_df.loc[prac_df["Batsman"]=="AC Gilchrist"]
d

        Batsman Strike Rate  key_cricinfo
0  AC Gilchrist         NaN          5390

In [162]:
df=pd.read_csv("/kaggle/working/Strike_Rates.csv")
df

           Batsman  Strike Rate  key_cricinfo
0     AC Gilchrist          NaN          5390
1    Azhar Mahmood          NaN         39024
2          M Vohra          NaN        532856
3    Mandeep Singh          NaN        398506
4        DA Miller          NaN        321777
..             ...          ...           ...
610   P Ray Barman          NaN       1159712
611   BE Hendricks          NaN        379927
612   TP Sudhindra          NaN         34139
613    C Ganapathy          NaN         28764
614  DJ Muthuswami          NaN        528985

[615 rows x 3 columns]

In [163]:
df["Strike Rate"]=df["Strike Rate"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Batsman       615 non-null    object
 1   Strike Rate   0 non-null      float64
 2   key_cricinfo  615 non-null    int64
dtypes: float64(1), int64(1), object(1)
memory usage: 14.5+ KB

In [158]:
d.loc[d["Batsman"]=="AC Gilchrist","key_cricinfo"].item()

88

In [170]:
float(get_strike_rate(df.loc[df["Batsman"]=="AC Gilchrist","key_cricinfo"].item()))

140.28

In [190]:
d=[]
for i in df["Batsman"]:
    print(i)
    v={}
    v[i]=float(get_strike_rate(df.loc[df["Batsman"]==i,"key_cricinfo"].item()))
    d.append(v)

AC Gilchrist
Azhar Mahmood
M Vohra
Mandeep Singh
DA Miller
RG Sharma
N Wadhera
C Green
SA Yadav
Tilak Varma
Vishnu Vinod
TH David
CJ Jordan
PP Chawla
K Kartikeya
JP Behrendorff
Q de Kock
Ishan Kishan
SS Tiwary
KH Pandya
HH Pandya
KA Pollard
G Gambhir
C de Grandhomme
RV Uthappa
MK Pandey
YK Pathan
CR Woakes
SP Narine
PA Patel
JC Buttler
N Rana
Washington Sundar
V Kohli
RM Patidar
GJ Maxwell
AB de Villiers
Shahbaz Ahmed
DT Christian
KA Jamieson
HV Patel
Mohammed Siraj
DR Smith
BB McCullum
SK Raina
F du Plessis
MS Dhoni
MS Bisla
DPMD Jayawardene
KC Sangakkara
Yuvraj Singh
Shahid Afridi
HH Gibbs
SB Styris
Y Venugopal Rao
DB Ravi Teja
RP Singh
PP Ojha
PM Sarvesh Kumar
DP Vijaykumar
DM Bravo
SV Samson
KK Nair
JP Duminy
RR Pant
CH Morris
P Negi
NJ Maddinson
S Dhawan
SR Tendulkar
R Sathish
DJ Bravo
R McLaren
MK Tiwary
SS Iyer
KM Jadhav
AD Mathews
JA Morkel
UBT Chand
DA Warner
LRPL Taylor
NV Ojha
AD Russell
IK Pathan
UT Yadav
BJ Hodge
SC Ganguly
WP Saha
OA Shah
LR Shukla
RS Gavaskar
SE Bond
M Kartik
I Sharma
SP Goswami
KS Williamson
PK Garg
JO Holder
YV Takawale
AM Rahane
ST Jayasuriya
AM Nayar
Harbhajan Singh
DS Kulkarni
C Nanda
SL Malinga
V Sehwag
GJ Bailey
BR Dunk
CJ Anderson
AT Rayudu
AP Tare
CM Gautam
Z Khan
LS Livingstone
SPD Smith
AJ Turner
S Badrinath
RA Jadeja
KMDN Kulasekara
R Ashwin
YBK Jaiswal
D Padikkal
SO Hetmyer
R Parag
KL Rahul
CH Gayle
MA Agarwal
AJ Finch
AR Patel
AJ Tye
BB Sran
MM Sharma
AA Bilakhia
TL Suman
A Symonds
CA Lynn
SR Watson
BA Stokes
RD Gaikwad
DP Conway
S Dube
P Kumar
JH Kallis
KP Pietersen
R Dravid
R Bishnoi
R Vinay Kumar
DW Steyn
A Kumble
Shakib Al Hasan
JD Ryder
GC Smith
AA Jhunjhunwala
M Manhas
SB Wagh
R Sharma
RA Tripathi
RR Rossouw
MA Starc
VR Aaron
AB Dinda
KS Bharat
JM Bairstow
V Shankar
Mohammad Nabi
Abdul Samad
Rashid Khan
Sandeep Sharma
B Kumar
D Brevis
Naman Dhir
R Shepherd
JR Philippe
Navdeep Saini
YS Chahal
TM Dilshan
A Mishra
MF Maharoof
VY Mahesh
PJ Sangwan
Shubman Gill
B Sai Sudharsan
R Tewatia
M Vijay
SE Marsh
R Dhawan
MG Johnson
Anureet Singh
SM Curran
DJ Hussey
ML Hayden
A Flintoff
JDP Oram
Joginder Sharma
T Thushara
Gurkeerat Singh
PR Shah
RR Raje
JEC Franklin
IR Jaggi
B Chipli
KD Karthik
JP Faulkner
MJ Lumb
FY Fazal
AC Voges
AS Raut
AP Dole
LMP Simmons
MEK Hussey
Dhruv Jurel
Rahmanullah Gurbaz
N Jagadeesan
VR Iyer
RK Singh
SN Thakur
Karanveer Singh
PP Shaw
MP Stoinis
Lalit Yadav
PC Valthaty
Bipul Sharma
RJ Harris
BR Sharath
DG Nalkande
SH Johnson
Noor Ahmad
LJ Wright
EJG Morgan
STR Binny
DR Sams
K Rabada
LA Carseldine
LPC Silva
H Das
DNT Zoysa
KV Sharma
AB Barath
RS Sodhi
RN ten Doeschate
MM Ali
DB Das
R Bhatia
SMSM Senanayake
Azmatullah Omarzai
M Shahrukh Khan
KK Ahmed
Shivam Mavi
Kuldeep Yadav
J Suchith
R Ravindra
DJ Mitchell
R Sai Kishore
A Ashish Reddy
DJG Sammy
GH Vihari
SB Dubey
KK Cooper
VS Malik
DJM Short
M Kaif
Younis Khan
Kamran Akmal
M Rawat
D Salunkhe
Pankaj Singh
GHS Garton
MD Mishra
SP Jackson
AC Blizzard
MM Patel
DL Chahar
MA Wood
Imran Tahir
SN Khan
D Wiese
Abhishek Sharma
N Pooran
AK Markram
Umran Malik
SE Rutherford
CA Ingram
AF Milne
S Badree
S Aravind
E Lewis
GD Phillips
Anuj Rawat
DJ Willey
PWH de Silva
RD Chahar
JJ Bumrah
TA Boult
S Sohal
CL White
MJ McClenaghan
Atharva Taide
MW Short
P Simran Singh
Harpreet Singh
JM Sharma
Harpreet Brar
NT Ellis
MN Samuels
MR Marsh
RK Bhui
T Stubbs
Abishek Porel
MJ Clarke
MK Lomror
K Gowtham
JC Archer
JJ Roy
CV Varun
SM Katich
S Anirudha
A Nehra
SW Billings
MC Henriques
DJ Hooda
BCJ Cutting
JDS Neesham
R Shukla
Mohammed Shami
Rasikh Salam
PBB Rajapaksa
Arshdeep Singh
S Kaul
AB Agarkar
CK Langeveldt
AUK Pathan
CA Pujara
JJ van der Wath
DL Vettori
Anmolpreet Singh
H Klaasen
Sanvir Singh
M Jansen
M Markande
Fazalhaq Farooqi
M Morkel
RS Bopara
Parvez Rasool
Shashank Singh
SA Asnodkar
SK Warne
Sohail Tanvir
C Munro
KW Richardson
AA Kulkarni
A Badoni
VG Arora
TM Head
Nithish Kumar Reddy
S Chanderpaul
MV Boucher
B Akhil
S Gopal
Kartik Tyagi
S Nadeem
R Sanjay Yadav
Ramandeep Singh
J Botha
AL Menaria
I Udana
KB Arun Karthik
A Mithun
PJ Cummins
RR Sarwan
WG Jacks
Saurav Chauhan
Vijaykumar Vyshak
B Indrajith
Sachin Baby
PV Tambe
SK Trivedi
K Goel
JR Hopes
HM Amla
MD Shanaka
A Manohar
VRV Singh
U Kaul
TG Southee
N Saini
SD Chitnis
B Lee
Iqbal Abdulla
L Balaji
J Fraser-McGurk
SD Hope
TM Srivastava
MC Juneja
T Kohler-Cadmore
R Powell
J Theron
RJ Peterson
TD Paine
M Muralitharan
A Nortje
Mukesh Kumar
AG Paunikar
RE van der Merwe
NS Naik
VVS Laxman
Jaskaran Singh
LA Pomersbach
WA Mota
RR Powar
MS Wade
AC Thomas
W Jaffer
RT Ponting
T Shamsi
Abdul Basith
SD Lad
AS Joseph
KR Mayers
JD Unadkat
Ravi Bishnoi
Avesh Khan
Y Nagar
M Ashwin
RP Meredith
Sumit Kumar
FA Allen
TS Mills
AD Hales
G Coetzee
SZ Mulani
MJ Santner
D Pretorius
KC Cariappa
Mohammad Hafeez
KP Appanna
RJ Quiney
PD Salt
RE Levi
SS Prabhudessai
WD Parnell
Mohammad Asif
GD McGrath
M Klinger
DR Shorey
A Zampa
DH Yagnik
CR Brathwaite
NLTC Perera
B Stanlake
A Choudhary
DJ Harris
PA Reddy
J Arunkumar
Misbah-ul-Haq
DT Patil
Abdur Razzak
D Ferreira
SM Harwood
MS Gony
LE Plunkett
Harmeet Singh
P Awana
AB McDonald
KS Sharma
Mohsin Khan
S Sriram
T Banton
KL Nagarkoti
M Prasidh Krishna
LH Ferguson
PN Mankad
WPUJC Vaas
Shoaib Ahmed
Tanush Kotian
KA Maharaj
A Tomar
TR Birt
AD Mascarenhas
B Sumanth
MG Bracewell
CRD Fernando
GC Viljoen
TL Seifert
L Wood
B Laughlin
SP Fleming
S Vidyut
M Ntini
TK Curran
AS Rajpoot
Mujeeb Ur Rahman
BJ Rohrer
Mustafizur Rahman
UT Khawaja
Arjun Tendulkar
Ashutosh Sharma
Sikandar Raza
AP Majumdar
CJ Ferguson
AG Murtaza
P Chopra
P Dogra
A Uniyal
Yudhvir Singh
P Parameswaran
JR Hazlewood
Ankit Sharma
Kumar Kushagra
JA Richardson
J Syed Mohammad
R Rampaul
S Randiv
DE Bollinger
BMAJ Mendis
AS Roy
Harshit Rana
Anirudh Singh
AD Nath
Basil Thampi
Mukesh Choudhary
SS Cottrell
SB Bangar
AS Yadav
AN Ahmed
F Behardien
T Natarajan
RV Gomez
S Sreesanth
PVD Chameera
IC Pandey
JE Root
KM Asif
L Ronchi
SM Pollock
MA Khote
S Ladda
DP Nannes
BB Samantray
Aman Hakim Khan
JM Kemp
RA Bawa
OF Smith
YV Dhull
HC Brook
DJ Jacobs
MJ Guptill
Swapnil Singh
Sunny Gupta
C Sakariya
Arshad Khan
Naveen-ul-Haq
PD Collingwood
CK Kapugedera
SJ Srivastava
S Lamichhane
NL McCullum
JE Taylor
Y Gnaneswara Rao
AA Noffke
SB Joshi
AU Rashid
VS Yeligati
DS Lehmann
AA Chavan
GB Hogg
Akash Deep
RV Patel
AT Carey
HR Shokeen
UA Birla
K Upadhyay
NM Coulter-Nile
KMA Paul
A Raghuvanshi
DJ Thornely
SA Abbott
BA Bhatt
BAW Mendis
A Mukund
Sunny Singh
Yashpal Singh
SS Shaikh
R Ninan
Mayank Dagar
RJW Topley
S Narwal
SW Tait
Sameer Rizvi
HE van der Dussen
KR Sen
Salman Butt
Umar Gul
TU Deshpande
MN van Wyk
DAJ Bracewell
A Kamboj
Shoaib Malik
S Kaushik
T Henderson
Kamran Khan
KAJ Roach
Virat Singh
A Chopra
Simarjeet Singh
M Theekshana
L Ablish
P Dubey
S Tyagi
AN Ghosh
P Ray Barman
BE Hendricks
TP Sudhindra
C Ganapathy
DJ Muthuswami

In [191]:
d

[{'AC Gilchrist': 140.28},
 {'Azhar Mahmood': 135.32},
 {'M Vohra': 128.27},
 {'Mandeep Singh': 128.66},
 {'DA Miller': 138.19},
 {'RG Sharma': 134.37},
 {'N Wadhera': 146.64},
 {'C Green': 149.21},
 {'SA Yadav': 152.67},
 {'Tilak Varma': 143.32},
 {'Vishnu Vinod': 142.69},
 {'TH David': 162.52},
 {'CJ Jordan': 132.69},
 {'PP Chawla': 123.52},
 {'K Kartikeya': 90.0},
 {'JP Behrendorff': 102.02},
 {'Q de Kock': 137.67},
 {'Ishan Kishan': 132.19},
 {'SS Tiwary': 122.17},
 {'KH Pandya': 131.56},
 {'HH Pandya': 139.2},
 {'KA Pollard': 150.98},
 {'G Gambhir': 120.58},
 {'C de Grandhomme': 155.62},
 {'RV Uthappa': 133.08},
 {'MK Pandey': 123.25},
 {'YK Pathan': 139.34},
 {'CR Woakes': 130.29},
 {'SP Narine': 149.24},
 {'PA Patel': 123.84},
 {'JC Buttler': 144.82},
 {'N Rana': 135.49},
 {'Washington Sundar': 120.17},
 {'V Kohli': 134.44},
 {'RM Patidar': 153.35},
 {'GJ Maxwell': 153.48},
 {'AB de Villiers': 150.13},
 {'Shahbaz Ahmed': 129.34},
 {'DT Christian': 137.73},
 {'KA Jamieson': 132.58},
 {'HV Patel': 142.79},
 {'Mohammed Siraj': 87.42},
 {'DR Smith': 127.42},
 {'BB McCullum': 136.49},
 {'SK Raina': 137.45},
 {'F du Plessis': 134.69},
 {'MS Dhoni': 135.64},
 {'MS Bisla': 110.7},
 {'DPMD Jayawardene': 132.02},
 {'KC Sangakkara': 126.42},
 {'Yuvraj Singh': 128.76},
 {'Shahid Afridi': 153.91},
 {'HH Gibbs': 123.14},
 {'SB Styris': 134.58},
 {'Y Venugopal Rao': 121.71},
 {'DB Ravi Teja': 108.59},
 {'RP Singh': 72.97},
 {'PP Ojha': 69.44},
 {'PM Sarvesh Kumar': 50.0},
 {'DP Vijaykumar': 120.0},
 {'DM Bravo': 116.39},
 {'SV Samson': 134.68},
 {'KK Nair': 132.41},
 {'JP Duminy': 122.66},
 {'RR Pant': 145.7},
 {'CH Morris': 150.04},
 {'P Negi': 122.22},
 {'NJ Maddinson': 123.11},
 {'S Dhawan': 125.34},
 {'SR Tendulkar': 121.08},
 {'R Sathish': 128.92},
 {'DJ Bravo': 125.46},
 {'R McLaren': 116.5},
 {'MK Tiwary': 116.43},
 {'SS Iyer': 131.3},
 {'KM Jadhav': 129.53},
 {'AD Mathews': 121.79},
 {'JA Morkel': 138.59},
 {'UBT Chand': 114.87},
 {'DA Warner': 140.1},
 {'LRPL Taylor': 130.89},
 {'NV Ojha': 118.78},
 {'AD Russell': 169.82},
 {'IK Pathan': 124.07},
 {'UT Yadav': 120.65},
 {'BJ Hodge': 131.28},
 {'SC Ganguly': 107.0},
 {'WP Saha': 127.95},
 {'OA Shah': 125.03},
 {'LR Shukla': 120.63},
 {'RS Gavaskar': 99.12},
 {'SE Bond': 103.22},
 {'M Kartik': 110.34},
 {'I Sharma': 77.9},
 {'SP Goswami': 115.55},
 {'KS Williamson': 122.66},
 {'PK Garg': 114.52},
 {'JO Holder': 128.62},
 {'YV Takawale': 105.4},
 {'AM Rahane': 121.67},
 {'ST Jayasuriya': 140.08},
 {'AM Nayar': 123.77},
 {'Harbhajan Singh': 128.35},
 {'DS Kulkarni': 100.0},
 {'C Nanda': 100.0},
 {'SL Malinga': 102.89},
 {'V Sehwag': 147.83},
 {'GJ Bailey': 131.47},
 {'BR Dunk': 129.63},
 {'CJ Anderson': 134.18},
 {'AT Rayudu': 124.24},
 {'AP Tare': 131.86},
 {'CM Gautam': 108.95},
 {'Z Khan': 86.42},
 {'LS Livingstone': 144.45},
 {'SPD Smith': 127.76},
 {'AJ Turner': 140.57},
 {'S Badrinath': 112.74},
 {'RA Jadeja': 130.22},
 {'KMDN Kulasekara': 120.06},
 {'R Ashwin': 119.88},
 {'YBK Jaiswal': 148.86},
 {'D Padikkal': 131.98},
 {'SO Hetmyer': 134.25},
 {'R Parag': 143.65},
 {'KL Rahul': 135.85},
 {'CH Gayle': 144.75},
 {'MA Agarwal': 133.46},
 {'AJ Finch': 138.16},
 {'AR Patel': 134.36},
 {'AJ Tye': 128.84},
 {'BB Sran': 132.5},
 {'MM Sharma': 97.1},
 {'AA Bilakhia': 107.71},
 {'TL Suman': 125.69},
 {'A Symonds': 147.35},
 {'CA Lynn': 142.42},
 {'SR Watson': 138.3},
 {'BA Stokes': 133.23},
 {'RD Gaikwad': 139.18},
 {'DP Conway': 128.58},
 {'S Dube': 142.55},
 {'P Kumar': 115.65},
 {'JH Kallis': 112.45},
 {'KP Pietersen': 136.89},
 {'R Dravid': 113.87},
 {'R Bishnoi': 137.48},
 {'R Vinay Kumar': 125.69},
 {'DW Steyn': 107.56},
 {'A Kumble': 77.96},
 {'Shakib Al Hasan': 124.84},
 {'JD Ryder': 145.25},
 {'GC Smith': 123.08},
 {'AA Jhunjhunwala': 103.96},
 {'M Manhas': 104.55},
 {'SB Wagh': 98.19},
 {'R Sharma': 98.49},
 {'RA Tripathi': 134.65},
 {'RR Rossouw': 143.86},
 {'MA Starc': 94.29},
 {'VR Aaron': 72.28},
 {'AB Dinda': 77.46},
 {'KS Bharat': 110.85},
 {'JM Bairstow': 137.85},
 {'V Shankar': 128.52},
 {'Mohammad Nabi': 136.64},
 {'Abdul Samad': 146.33},
 {'Rashid Khan': 144.7},
 {'Sandeep Sharma': 85.24},
 {'B Kumar': 92.15},
 {'D Brevis': 140.14},
 {'Naman Dhir': 167.28},
 {'R Shepherd': 151.94},
 {'JR Philippe': 133.67},
 {'Navdeep Saini': 81.81},
 {'YS Chahal': 53.02},
 {'TM Dilshan': 122.82},
 {'A Mishra': 96.88},
 {'MF Maharoof': 117.91},
 {'VY Mahesh': 105.49},
 {'PJ Sangwan': 108.26},
 {'Shubman Gill': 137.18},
 {'B Sai Sudharsan': 130.69},
 {'R Tewatia': 143.04},
 {'M Vijay': 122.19},
 {'SE Marsh': 128.53},
 {'R Dhawan': 122.11},
 {'MG Johnson': 105.26},
 {'Anureet Singh': 108.88},
 {'SM Curran': 132.29},
 {'DJ Hussey': 133.2},
 {'ML Hayden': 136.91},
 {'A Flintoff': 142.88},
 {'JDP Oram': 126.1},
 {'Joginder Sharma': 126.11},
 {'T Thushara': 111.48},
 {'Gurkeerat Singh': 123.66},
 {'PR Shah': 110.55},
 {'RR Raje': 96.42},
 {'JEC Franklin': 124.73},
 {'IR Jaggi': 121.95},
 {'B Chipli': 117.35},
 {'KD Karthik': 136.96},
 {'JP Faulkner': 125.03},
 {'MJ Lumb': 137.91},
 {'FY Fazal': 106.17},
 {'AC Voges': 126.88},
 {'AS Raut': 111.6},
 {'AP Dole': 154.54},
 {'LMP Simmons': 119.19},
 {'MEK Hussey': 124.9},
 {'Dhruv Jurel': 137.61},
 {'Rahmanullah Gurbaz': 148.62},
 {'N Jagadeesan': 118.78},
 {'VR Iyer': 139.15},
 {'RK Singh': 148.13},
 {'SN Thakur': 130.05},
 {'Karanveer Singh': 66.66},
 {'PP Shaw': 151.2},
 {'MP Stoinis': 138.12},
 {'Lalit Yadav': 135.13},
 {'PC Valthaty': 126.5},
 {'Bipul Sharma': 138.59},
 {'RJ Harris': 103.46},
 {'BR Sharath': 117.43},
 {'DG Nalkande': 99.3},
 {'SH Johnson': 92.3},
 {'Noor Ahmad': 105.51},
 {'LJ Wright': 142.81},
 {'EJG Morgan': 131.59},
 {'STR Binny': 126.13},
 {'DR Sams': 150.35},
 {'K Rabada': 106.17},
 {'LA Carseldine': 125.21},
 {'LPC Silva': 122.57},
 {'H Das': 96.84},
 {'DNT Zoysa': 118.02},
 {'KV Sharma': 126.28},
 {'AB Barath': 106.5},
 {'RS Sodhi': 81.81},
 {'RN ten Doeschate': 133.56},
 {'MM Ali': 140.42},
 {'DB Das': 128.39},
 {'R Bhatia': 115.94},
 {'SMSM Senanayake': 107.91},
 {'Azmatullah Omarzai': 130.74},
 {'M Shahrukh Khan': 137.01},
 {'KK Ahmed': 34.48},
 {'Shivam Mavi': 94.44},
 {'Kuldeep Yadav': 86.37},
 {'J Suchith': 122.08},
 {'R Ravindra': 133.38},
 {'DJ Mitchell': 135.72},
 {'R Sai Kishore': 115.68},
 {'A Ashish Reddy': 126.89},
 {'DJG Sammy': 138.39},
 {'GH Vihari': 115.72},
 {'SB Dubey': 146.74},
 {'KK Cooper': 138.92},
 {'VS Malik': 113.17},
 {'DJM Short': 129.71},
 {'M Kaif': 102.99},
 {'Younis Khan': 117.3},
 {'Kamran Akmal': 133.73},
 {'M Rawat': 122.65},
 {'D Salunkhe': 137.5},
 {'Pankaj Singh': 68.36},
 {'GHS Garton': 135.76},
 {'MD Mishra': 133.18},
 {'SP Jackson': 120.07},
 {'AC Blizzard': 132.57},
 {'MM Patel': 78.33},
 {'DL Chahar': 137.36},
 {'MA Wood': 108.25},
 {'Imran Tahir': 106.04},
 {'SN Khan': 128.29},
 {'D Wiese': 144.23},
 {'Abhishek Sharma': 153.59},
 {'N Pooran': 147.22},
 {'AK Markram': 132.18},
 {'Umran Malik': 114.99},
 {'SE Rutherford': 134.43},
 {'CA Ingram': 137.96},
 {'AF Milne': 117.69},
 {'S Badree': 81.33},
 {'S Aravind': 100.0},
 {'E Lewis': 144.37},
 {'GD Phillips': 141.01},
 {'Anuj Rawat': 118.19},
 {'DJ Willey': 134.96},
 {'PWH de Silva': 143.92},
 {'RD Chahar': 102.7},
 {'JJ Bumrah': 87.17},
 {'TA Boult': 102.45},
 {'S Sohal': 113.91},
 {'CL White': 126.33},
 {'MJ McClenaghan': 115.31},
 {'Atharva Taide': 140.67},
 {'MW Short': 143.28},
 {'P Simran Singh': 143.54},
 {'Harpreet Singh': 122.81},
 {'JM Sharma': 147.59},
 {'Harpreet Brar': 122.18},
 {'NT Ellis': 111.69},
 {'MN Samuels': 117.93},
 {'MR Marsh': 132.41},
 {'RK Bhui': 137.48},
 {'T Stubbs': 152.4},
 {'Abishek Porel': 149.63},
 {'MJ Clarke': 108.22},
 {'MK Lomror': 129.03},
 {'K Gowtham': 158.18},
 {'JC Archer': 147.04},
 {'JJ Roy': 141.6},
 {'CV Varun': 46.96},
 {'SM Katich': 126.61},
 {'S Anirudha': 124.57},
 {'A Nehra': 67.64},
 {'SW Billings': 132.77},
 {'MC Henriques': 127.56},
 {'DJ Hooda': 137.82},
 {'BCJ Cutting': 145.25},
 {'JDS Neesham': 142.33},
 {'R Shukla': 98.8},
 {'Mohammed Shami': 90.52},
 {'Rasikh Salam': 91.04},
 {'PBB Rajapaksa': 135.89},
 {'Arshdeep Singh': 97.33},
 {'S Kaul': 87.2},
 {'AB Agarkar': 125.43},
 {'CK Langeveldt': 85.41},
 {'AUK Pathan': 148.75},
 {'CA Pujara': 112.18},
 {'JJ van der Wath': 127.51},
 {'DL Vettori': 119.65},
 {'Anmolpreet Singh': 129.04},
 {'H Klaasen': 151.62},
 {'Sanvir Singh': 187.05},
 {'M Jansen': 135.26},
 {'M Markande': 114.44},
 {'Fazalhaq Farooqi': 31.42},
 {'M Morkel': 108.67},
 {'RS Bopara': 122.61},
 {'Parvez Rasool': 105.66},
 {'Shashank Singh': 144.11},
 {'SA Asnodkar': 124.19},
 {'SK Warne': 92.1},
 {'Sohail Tanvir': 120.56},
 {'C Munro': 141.25},
 {'KW Richardson': 113.25},
 {'AA Kulkarni': 158.53},
 {'A Badoni': 135.13},
 {'VG Arora': 61.11},
 {'TM Head': 142.62},
 {'Nithish Kumar Reddy': 128.24},
 {'S Chanderpaul': 105.77},
 {'MV Boucher': 115.41},
 {'B Akhil': 148.61},
 {'S Gopal': 119.24},
 {'Kartik Tyagi': 81.25},
 {'S Nadeem': 89.38},
 {'R Sanjay Yadav': 118.95},
 {'Ramandeep Singh': 166.05},
 {'J Botha': 113.06},
 {'AL Menaria': 115.67},
 {'I Udana': 129.45},
 {'KB Arun Karthik': 124.0},
 {'A Mithun': 122.42},
 {'PJ Cummins': 138.44},
 {'RR Sarwan': 103.81},
 {'WG Jacks': 158.95},
 {'Saurav Chauhan': 150.62},
 {'Vijaykumar Vyshak': 106.06},
 {'B Indrajith': 101.49},
 {'Sachin Baby': 130.86},
 {'PV Tambe': 52.77},
 {'SK Trivedi': 92.2},
 {'K Goel': 91.88},
 {'JR Hopes': 124.09},
 {'HM Amla': 126.04},
 {'MD Shanaka': 140.07},
 {'A Manohar': 149.4},
 {'VRV Singh': 125.8},
 {'U Kaul': 97.68},
 {'TG Southee': 140.34},
 {'N Saini': 101.77},
 {'SD Chitnis': 153.15},
 {'B Lee': 131.23},
 {'Iqbal Abdulla': 99.3},
 {'L Balaji': 87.09},
 {'J Fraser-McGurk': 156.25},
 {'SD Hope': 127.72},
 {'TM Srivastava': 116.3},
 {'MC Juneja': 126.59},
 {'T Kohler-Cadmore': 138.96},
 {'R Powell': 139.45},
 {'J Theron': 108.71},
 {'RJ Peterson': 111.6},
 {'TD Paine': 122.27},
 {'M Muralitharan': 73.63},
 {'A Nortje': 96.55},
 {'Mukesh Kumar': 68.96},
 {'AG Paunikar': 113.76},
 {'RE van der Merwe': 131.8},
 {'NS Naik': 128.13},
 {'VVS Laxman': 114.71},
 {'Jaskaran Singh': 146.57},
 {'LA Pomersbach': 129.8},
 {'WA Mota': 91.56},
 {'RR Powar': 102.85},
 {'MS Wade': 136.47},
 {'AC Thomas': 106.77},
 {'W Jaffer': 129.14},
 {'RT Ponting': 110.98},
 {'T Shamsi': 53.84},
 {'Abdul Basith': 139.37},
 {'SD Lad': 118.86},
 {'AS Joseph': 104.76},
 {'KR Mayers': 131.07},
 {'JD Unadkat': 131.64},
 {'Ravi Bishnoi': 87.31},
 {'Avesh Khan': 120.0},
 {'Y Nagar': 106.88},
 {'M Ashwin': 85.38},
 {'RP Meredith': 96.77},
 {'Sumit Kumar': 131.55},
 {'FA Allen': 142.85},
 {'TS Mills': 92.59},
 {'AD Hales': 146.16},
 {'G Coetzee': 110.69},
 {'SZ Mulani': 114.02},
 {'MJ Santner': 132.04},
 {'D Pretorius': 137.27},
 {'KC Cariappa': 118.39},
 {'Mohammad Hafeez': 123.65},
 {'KP Appanna': 130.0},
 {'RJ Quiney': 121.97},
 {'PD Salt': 155.47},
 {'RE Levi': 144.03},
 {'SS Prabhudessai': 134.08},
 {'WD Parnell': 123.24},
 {'Mohammad Asif': 86.66},
 {'GD McGrath': 50.0},
 {'M Klinger': 123.08},
 {'DR Shorey': 118.11},
 {'A Zampa': 85.54},
 {'DH Yagnik': 116.96},
 {'CR Brathwaite': 136.31},
 {'NLTC Perera': 150.92},
 {'B Stanlake': 65.21},
 {'A Choudhary': 94.17},
 {'DJ Harris': 127.43},
 {'PA Reddy': 123.15},
 {'J Arunkumar': 101.28},
 {'Misbah-ul-Haq': 116.48},
 {'DT Patil': 113.94},
 {'Abdur Razzak': 85.89},
 {'D Ferreira': 152.24},
 {'SM Harwood': 132.89},
 {'MS Gony': 149.55},
 {'LE Plunkett': 130.95},
 {'Harmeet Singh': 188.88},
 {'P Awana': 51.16},
 {'AB McDonald': 124.41},
 {'KS Sharma': 116.25},
 {'Mohsin Khan': 111.11},
 {'S Sriram': 99.57},
 {'T Banton': 141.54},
 {'KL Nagarkoti': 81.03},
 {'M Prasidh Krishna': 34.48},
 {'LH Ferguson': 115.11},
 {'PN Mankad': 141.19},
 {'WPUJC Vaas': 110.52},
 {'Shoaib Ahmed': 16.66},
 {'Tanush Kotian': 101.17},
 {'KA Maharaj': 115.29},
 {'A Tomar': 114.33},
 {'TR Birt': 129.0},
 {'AD Mascarenhas': 127.32},
 {'B Sumanth': 122.66},
 {'MG Bracewell': 133.63},
 {'CRD Fernando': 92.15},
 {'GC Viljoen': 129.07},
 {'TL Seifert': 129.69},
 {'L Wood': 114.18},
 {'B Laughlin': 90.52},
 {'SP Fleming': 121.91},
 {'S Vidyut': 129.74},
 {'M Ntini': 69.76},
 {'TK Curran': 142.24},
 {'AS Rajpoot': 75.0},
 {'Mujeeb Ur Rahman': 103.07},
 {'BJ Rohrer': 133.09},
 {'Mustafizur Rahman': 77.29},
 {'UT Khawaja': 130.39},
 {'Arjun Tendulkar': 118.07},
 {'Ashutosh Sharma': 187.07},
 {'Sikandar Raza': 134.09},
 {'AP Majumdar': 103.95},
 {'CJ Ferguson': 124.83},
 {'AG Murtaza': 86.23},
 {'P Chopra': 114.71},
 {'P Dogra': 115.6},
 {'A Uniyal': 75.0},
 {'Yudhvir Singh': 186.56},
 {'P Parameswaran': 75.0},
 {'JR Hazlewood': 92.75},
 {'Ankit Sharma': 102.7},
 {'Kumar Kushagra': 113.49},
 {'JA Richardson': 109.41},
 {'J Syed Mohammad': 110.71},
 {'R Rampaul': 104.09},
 {'S Randiv': 138.82},
 {'DE Bollinger': 95.83},
 {'BMAJ Mendis': 123.62},
 {'AS Roy': 146.89},
 {'Harshit Rana': 66.66},
 {'Anirudh Singh': 89.81},
 {'AD Nath': 115.52},
 {'Basil Thampi': 108.95},
 {'Mukesh Choudhary': 121.05},
 {'SS Cottrell': 114.85},
 {'SB Bangar': 124.5},
 {'AS Yadav': 111.23},
 {'AN Ahmed': 111.57},
 {'F Behardien': 131.13},
 {'T Natarajan': 53.33},
 {'RV Gomez': 128.78},
 {'S Sreesanth': 76.84},
 {'PVD Chameera': 96.66},
 {'IC Pandey': 123.86},
 {'JE Root': 127.14},
 {'KM Asif': 33.33},
 {'L Ronchi': 153.51},
 {'SM Pollock': 141.89},
 {'MA Khote': 137.38},
 {'S Ladda': 41.66},
 {'DP Nannes': 83.54},
 {'BB Samantray': 117.05},
 {'Aman Hakim Khan': 136.26},
 {'JM Kemp': 124.44},
 {'RA Bawa': 117.09},
 {'OF Smith': 133.21},
 {'YV Dhull': 127.27},
 {'HC Brook': 149.61},
 {'DJ Jacobs': 117.56},
 {'MJ Guptill': 130.43},
 {'Swapnil Singh': 127.29},
 {'Sunny Gupta': 96.42},
 {'C Sakariya': 59.52},
 {'Arshad Khan': 132.6},
 {'Naveen-ul-Haq': 96.36},
 {'PD Collingwood': 121.47},
 {'CK Kapugedera': 129.44},
 {'SJ Srivastava': 85.71},
 {'S Lamichhane': 86.98},
 {'NL McCullum': 125.91},
 {'JE Taylor': 120.9},
 {'Y Gnaneswara Rao': 123.98},
 {'AA Noffke': 139.15},
 {'SB Joshi': 90.69},
 {'AU Rashid': 106.69},
 {'VS Yeligati': 120.0},
 {'DS Lehmann': 117.95},
 {'AA Chavan': 128.33},
 {'GB Hogg': 105.4},
 {'Akash Deep': 144.44},
 {'RV Patel': 145.11},
 {'AT Carey': 127.98},
 {'HR Shokeen': 106.06},
 {'UA Birla': 107.94},
 {'K Upadhyay': 92.68},
 {'NM Coulter-Nile': 129.77},
 {'KMA Paul': 126.59},
 {'A Raghuvanshi': 134.37},
 {'DJ Thornely': 117.87},
 {'SA Abbott': 122.08},
 {'BA Bhatt': 123.28},
 {'BAW Mendis': 86.99},
 {'A Mukund': 110.3},
 {'Sunny Singh': 119.32},
 {'Yashpal Singh': 106.74},
 {'SS Shaikh': 121.25},
 {'R Ninan': 50.0},
 {'Mayank Dagar': 74.22},
 {'RJW Topley': 92.66},
 {'S Narwal': 162.94},
 {'SW Tait': 81.09},
 {'Sameer Rizvi': 132.06},
 {'HE van der Dussen': 131.96},
 {'KR Sen': 15.38},
 {'Salman Butt': 112.98},
 {'Umar Gul': 103.2},
 {'TU Deshpande': 115.78},
 {'MN van Wyk': 125.94},
 {'DAJ Bracewell': 154.35},
 {'A Kamboj': 92.3},
 {'Shoaib Malik': 127.56},
 {'S Kaushik': 0.0},
 {'T Henderson': 142.9},
 {'Kamran Khan': 122.22},
 {'KAJ Roach': 113.46},
 {'Virat Singh': 127.42},
 {'A Chopra': 91.25},
 {'Simarjeet Singh': 69.23},
 {'M Theekshana': 69.95},
 {'L Ablish': 50.0},
 {'P Dubey': 99.3},
 {'S Tyagi': 71.42},
 {'AN Ghosh': 100.0},
 {'P Ray Barman': 105.0},
 {'BE Hendricks': 86.99},
 {'TP Sudhindra': 94.93},
 {'C Ganapathy': 94.87},
 {'DJ Muthuswami': 52.38}]

In [196]:
f={'DJ Muthuswami': 52.38}
list(f.keys())[0],list(f.values())[0]

('DJ Muthuswami', 52.38)

In [197]:
dr={"Batsman":[],"Strike_Rate":[]}
for i in d:
    dr["Batsman"].append(list(i.keys())[0])
    dr["Strike_Rate"].append(list(i.values())[0])

In [199]:
st_df=pd.DataFrame(dr)
st_df

           Batsman  Strike_Rate
0     AC Gilchrist       140.28
1    Azhar Mahmood       135.32
2          M Vohra       128.27
3    Mandeep Singh       128.66
4        DA Miller       138.19
..             ...          ...
610   P Ray Barman       105.00
611   BE Hendricks        86.99
612   TP Sudhindra        94.93
613    C Ganapathy        94.87
614  DJ Muthuswami        52.38

[615 rows x 2 columns]

In [201]:
st_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Batsman      615 non-null    object
 1   Strike_Rate  615 non-null    float64
dtypes: float64(1), object(1)
memory usage: 9.7+ KB

In [200]:
st_df.to_csv("Strike_Rates1.csv",index=False)

In [202]:
deliveries=pd.read_csv("/kaggle/working/Deliveries.csv")
deliveries

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner
0,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1
1,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1
2,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1
3,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1
4,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122322,1178419,MJ Santner,Harbhajan Singh,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0
122323,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0
122324,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0
122325,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0
122326,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0

In [203]:
st_df

           Batsman  Strike_Rate
0     AC Gilchrist       140.28
1    Azhar Mahmood       135.32
2          M Vohra       128.27
3    Mandeep Singh       128.66
4        DA Miller       138.19
..             ...          ...
610   P Ray Barman       105.00
611   BE Hendricks        86.99
612   TP Sudhindra        94.93
613    C Ganapathy        94.87
614  DJ Muthuswami        52.38

[615 rows x 2 columns]

In [204]:
st_df["batter"]=st_df["Batsman"]

In [206]:
st_df["non_striker"]=st_df["Batsman"]

In [207]:
st_df

           Batsman  Strike_Rate         batter    non_striker
0     AC Gilchrist       140.28   AC Gilchrist   AC Gilchrist
1    Azhar Mahmood       135.32  Azhar Mahmood  Azhar Mahmood
2          M Vohra       128.27        M Vohra        M Vohra
3    Mandeep Singh       128.66  Mandeep Singh  Mandeep Singh
4        DA Miller       138.19      DA Miller      DA Miller
..             ...          ...            ...            ...
610   P Ray Barman       105.00   P Ray Barman   P Ray Barman
611   BE Hendricks        86.99   BE Hendricks   BE Hendricks
612   TP Sudhindra        94.93   TP Sudhindra   TP Sudhindra
613    C Ganapathy        94.87    C Ganapathy    C Ganapathy
614  DJ Muthuswami        52.38  DJ Muthuswami  DJ Muthuswami

[615 rows x 4 columns]

In [208]:
pred_df=pd.merge(deliveries,st_df[["batter","Strike_Rate"]],on="batter")
pred_df

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate
0,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1,140.28
1,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1,140.28
2,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1,140.28
3,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1,135.32
4,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1,135.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122184,1178419,MJ Santner,Harbhajan Singh,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04
122185,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35
122186,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35
122187,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04
122188,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04

In [209]:
pred_df=pd.merge(pred_df,st_df[["non_striker","Strike_Rate"]],on="non_striker")
pred_df

,Match_id,batter,non_striker,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate_x,Strike_Rate_y
0,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1,140.28,128.66
1,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1,140.28,128.66
2,598025,AC Gilchrist,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1,140.28,128.66
3,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1,135.32,128.66
4,598025,Azhar Mahmood,Mandeep Singh,Kings XI Punjab,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1,135.32,128.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122075,1178419,MJ Santner,Harbhajan Singh,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04,128.35
122076,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35,132.04
122077,1178419,Harbhajan Singh,MJ Santner,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35,132.04
122078,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04,106.04
122079,1178419,MJ Santner,Imran Tahir,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04,106.04

In [210]:
final_df=pred_df.drop(columns=["batter","non_striker"])
final_df

,Match_id,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate_x,Strike_Rate_y
0,598025,Kings XI Punjab,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1,140.28,128.66
1,598025,Kings XI Punjab,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1,140.28,128.66
2,598025,Kings XI Punjab,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1,140.28,128.66
3,598025,Kings XI Punjab,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1,135.32,128.66
4,598025,Kings XI Punjab,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1,135.32,128.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122075,1178419,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04,128.35
122076,1178419,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35,132.04
122077,1178419,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35,132.04
122078,1178419,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04,106.04
122079,1178419,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04,106.04

In [212]:
final_df=final_df.drop(columns=["Match_id"])
final_df

,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate_x,Strike_Rate_y
0,Kings XI Punjab,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1,140.28,128.66
1,Kings XI Punjab,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1,140.28,128.66
2,Kings XI Punjab,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1,140.28,128.66
3,Kings XI Punjab,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1,135.32,128.66
4,Kings XI Punjab,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1,135.32,128.66
...,...,...,...,...,...,...,...,...,...,...,...,...
122075,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04,128.35
122076,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35,132.04
122077,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35,132.04
122078,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04,106.04
122079,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04,106.04

In [215]:
final_df["batting_team"].unique()

array(['Kings XI Punjab', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Royal Challengers Bangalore', 'Chennai Super Kings',
       'Deccan Chargers', 'Delhi Daredevils', 'Sunrisers Hyderabad',
       'Rajasthan Royals', 'Pune Warriors', 'Rising Pune Supergiant',
       'Gujarat Titans', 'Gujarat Lions', 'Delhi Capitals',
       'Punjab Kings', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru', 'Kochi Tuskers Kerala',
       'Rising Pune Supergiants'], dtype=object)

In [217]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122080 entries, 0 to 122079
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   batting_team   122080 non-null  object
 1   bowling_team   122080 non-null  object
 2   target         122080 non-null  int64
 3   balls_left     122080 non-null  int64
 4   wickets_left   122080 non-null  int64
 5   runs_left      122080 non-null  int64
 6   crr            122080 non-null  float64
 7   rrr            122080 non-null  float64
 8   Venue          122080 non-null  object
 9   Winner         122080 non-null  int64
 10  Strike_Rate_x  122080 non-null  float64
 11  Strike_Rate_y  122080 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 11.2+ MB

In [216]:
final_df.to_csv("Final_Data_IPL.csv",index=False)

In [218]:
final_df["batting_team"]=final_df["batting_team"].str.replace("Delhi Daredevils","Delhi Capitals")
final_df["bowling_team"]=final_df["bowling_team"].str.replace("Delhi Daredevils","Delhi Capitals")

final_df["batting_team"]=final_df["batting_team"].str.replace("Deccan Chargers","Sunrisers Hyderabad")
final_df["bowling_team"]=final_df["bowling_team"].str.replace("Deccan Chargers","Sunrisers Hyderabad")

final_df["batting_team"]=final_df["batting_team"].str.replace("Kings XI Punjab","Punjab Kings")
final_df["bowling_team"]=final_df["bowling_team"].str.replace("Kings XI Punjab","Punjab Kings")

final_df

,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate_x,Strike_Rate_y
0,Punjab Kings,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1,140.28,128.66
1,Punjab Kings,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1,140.28,128.66
2,Punjab Kings,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1,140.28,128.66
3,Punjab Kings,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1,135.32,128.66
4,Punjab Kings,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1,135.32,128.66
...,...,...,...,...,...,...,...,...,...,...,...,...
122075,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04,128.35
122076,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35,132.04
122077,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35,132.04
122078,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04,106.04
122079,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04,106.04

In [219]:
final_df["batting_team"]=final_df["batting_team"].str.replace("Royal Challengers Bangalore","Royal Challengers Bengaluru")
final_df["bowling_team"]=final_df["bowling_team"].str.replace("Royal Challengers Bangalore","Royal Challengers Bengaluru")

final_df

,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate_x,Strike_Rate_y
0,Punjab Kings,Pune Warriors,186,119,10,186,0.000000,9.377363,Mohali,1,140.28,128.66
1,Punjab Kings,Pune Warriors,186,118,10,182,12.000000,9.253453,Mohali,1,140.28,128.66
2,Punjab Kings,Pune Warriors,186,117,9,182,8.000000,9.332536,Mohali,1,140.28,128.66
3,Punjab Kings,Pune Warriors,186,116,9,182,6.000000,9.412982,Mohali,1,135.32,128.66
4,Punjab Kings,Pune Warriors,186,115,9,182,4.800000,9.494827,Mohali,1,135.32,128.66
...,...,...,...,...,...,...,...,...,...,...,...,...
122075,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04,128.35
122076,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35,132.04
122077,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35,132.04
122078,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04,106.04
122079,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04,106.04

In [221]:
final_df["batting_team"].unique()

array(['Punjab Kings', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Royal Challengers Bengaluru', 'Chennai Super Kings',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Rajasthan Royals',
       'Pune Warriors', 'Rising Pune Supergiant', 'Gujarat Titans',
       'Gujarat Lions', 'Lucknow Super Giants', 'Kochi Tuskers Kerala',
       'Rising Pune Supergiants'], dtype=object)

In [222]:
teams=["Mumbai Indians","Chennai Super Kings","Kolkata Knight Riders","Royal Challengers Bengaluru","Punjab Kings","Sunrisers Hyderabad","Delhi Capitals","Rajasthan Royals","Lucknow Super Giants","Gujarat Titans"]

In [223]:
for i in teams:
    print(i)

Mumbai Indians
Chennai Super Kings
Kolkata Knight Riders
Royal Challengers Bengaluru
Punjab Kings
Sunrisers Hyderabad
Delhi Capitals
Rajasthan Royals
Lucknow Super Giants
Gujarat Titans

In [224]:
final_df.to_csv("Final_Data_IPL1.csv",index=False)

In [225]:
final_df=final_df[final_df["batting_team"].isin(teams)]
final_df=final_df[final_df["bowling_team"].isin(teams)]

final_df

,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Winner,Strike_Rate_x,Strike_Rate_y
120,Mumbai Indians,Gujarat Titans,234,119,10,234,0.000000,11.797328,Ahmedabad,0,134.37,146.64
121,Mumbai Indians,Gujarat Titans,234,118,10,233,3.000000,11.846454,Ahmedabad,0,134.37,146.64
122,Mumbai Indians,Gujarat Titans,234,117,10,233,2.000000,11.947697,Ahmedabad,0,146.64,134.37
123,Mumbai Indians,Gujarat Titans,234,116,10,229,7.500000,11.843807,Ahmedabad,0,146.64,134.37
124,Mumbai Indians,Gujarat Titans,234,115,9,229,6.000000,11.946787,Ahmedabad,0,146.64,134.37
...,...,...,...,...,...,...,...,...,...,...,...,...
122075,Chennai Super Kings,Mumbai Indians,156,18,2,53,6.058824,17.656857,Chennai,0,132.04,128.35
122076,Chennai Super Kings,Mumbai Indians,156,17,2,53,6.000000,18.694885,Chennai,0,128.35,132.04
122077,Chennai Super Kings,Mumbai Indians,156,16,1,53,5.942308,19.862586,Chennai,0,128.35,132.04
122078,Chennai Super Kings,Mumbai Indians,156,15,1,47,6.228571,18.787475,Chennai,0,132.04,106.04
122079,Chennai Super Kings,Mumbai Indians,156,14,0,47,6.169811,20.128480,Chennai,0,132.04,106.04

In [248]:
final_df.to_csv("Final Processed Data.csv",index=False)

In [229]:
list(final_df["batting_team"].unique())

['Mumbai Indians',
 'Kolkata Knight Riders',
 'Royal Challengers Bengaluru',
 'Chennai Super Kings',
 'Punjab Kings',
 'Sunrisers Hyderabad',
 'Delhi Capitals',
 'Rajasthan Royals',
 'Gujarat Titans',
 'Lucknow Super Giants']

In [231]:
final_df["Winner"].value_counts()

Winner
1    56307
0    53228
Name: count, dtype: int64

In [232]:
from sklearn.model_selection import train_test_split

In [233]:
x=final_df.drop(columns=["Winner"])
y=final_df["Winner"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [234]:
x_train

,batting_team,bowling_team,target,balls_left,wickets_left,runs_left,crr,rrr,Venue,Strike_Rate_x,Strike_Rate_y
52151,Rajasthan Royals,Punjab Kings,125,119,10,121,24.000000,6.100328,Jaipur,138.30,121.67
118977,Sunrisers Hyderabad,Delhi Capitals,145,44,7,70,5.921053,9.543286,Hyderabad,132.18,153.59
22942,Punjab Kings,Mumbai Indians,173,79,8,124,7.170732,9.416530,Mohali,122.19,138.19
65498,Delhi Capitals,Rajasthan Royals,142,84,8,82,10.000000,5.856446,Ahmedabad,147.83,150.13
46074,Delhi Capitals,Sunrisers Hyderabad,176,50,6,74,8.742857,8.878224,Hyderabad,147.83,124.07
...,...,...,...,...,...,...,...,...,...,...,...
60270,Chennai Super Kings,Mumbai Indians,165,101,10,139,8.210526,8.256608,Mumbai,124.90,122.19
86037,Punjab Kings,Sunrisers Hyderabad,191,75,7,135,7.466667,10.798560,Mohali,133.20,135.32
115424,Sunrisers Hyderabad,Delhi Capitals,115,48,7,52,5.250000,6.498646,Delhi,115.72,126.33
980,Sunrisers Hyderabad,Delhi Capitals,195,73,8,121,9.446809,9.943843,Delhi,123.14,134.37
17724,Royal Challengers Bengaluru,Chennai Super Kings,184,23,5,60,7.670103,15.645372,Chennai,112.18,150.13

In [250]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [240]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','Venue'])
]
,remainder='passthrough')

In [237]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [241]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [242]:
pipe.fit(x_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'Venue'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [243]:
y_pred = pipe.predict(x_test)

In [244]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8034874697585247

In [245]:
pipe.predict_proba(x_test)[10]

array([0.5584648, 0.4415352])

In [247]:
import pickle
pickle.dump(pipe,open('IPL_Model.pkl','wb'))

In [249]:
final_df["Venue"].unique()

array(['Ahmedabad', 'Abu Dhabi', 'Delhi', 'Indore', 'Chennai', 'Dubai',
       'Kolkata', 'Mumbai', 'Durban', 'Mohali', 'Jaipur', 'Centurion',
       'Bangalore', 'Port Elizabeth', 'Cape Town', 'Lucknow', 'Hyderabad',
       'Raipur', 'Johannesburg', 'Sharjah', 'Mullanpur', 'Nagpur', 'Pune',
       'Cuttack', 'Dharamsala', 'Bengaluru', 'Guwahati', 'Visakhapatnam',
       'Bloemfontein', 'Ranchi', 'East London', 'Kimberley'], dtype=object)

In [268]:
st_df["Batsman"].unique()

array(['AC Gilchrist', 'Azhar Mahmood', 'M Vohra', 'Mandeep Singh',
       'DA Miller', 'RG Sharma', 'N Wadhera', 'C Green', 'SA Yadav',
       'Tilak Varma', 'Vishnu Vinod', 'TH David', 'CJ Jordan',
       'PP Chawla', 'K Kartikeya', 'JP Behrendorff', 'Q de Kock',
       'Ishan Kishan', 'SS Tiwary', 'KH Pandya', 'HH Pandya',
       'KA Pollard', 'G Gambhir', 'C de Grandhomme', 'RV Uthappa',
       'MK Pandey', 'YK Pathan', 'CR Woakes', 'SP Narine', 'PA Patel',
       'JC Buttler', 'N Rana', 'Washington Sundar', 'V Kohli',
       'RM Patidar', 'GJ Maxwell', 'AB de Villiers', 'Shahbaz Ahmed',
       'DT Christian', 'KA Jamieson', 'HV Patel', 'Mohammed Siraj',
       'DR Smith', 'BB McCullum', 'SK Raina', 'F du Plessis', 'MS Dhoni',
       'MS Bisla', 'DPMD Jayawardene', 'KC Sangakkara', 'Yuvraj Singh',
       'Shahid Afridi', 'HH Gibbs', 'SB Styris', 'Y Venugopal Rao',
       'DB Ravi Teja', 'RP Singh', 'PP Ojha', 'PM Sarvesh Kumar',
       'DP Vijaykumar', 'DM Bravo', 'SV Samson', 'KK Nair', 'JP Duminy',
       'RR Pant', 'CH Morris', 'P Negi', 'NJ Maddinson', 'S Dhawan',
       'SR Tendulkar', 'R Sathish', 'DJ Bravo', 'R McLaren', 'MK Tiwary',
       'SS Iyer', 'KM Jadhav', 'AD Mathews', 'JA Morkel', 'UBT Chand',
       'DA Warner', 'LRPL Taylor', 'NV Ojha', 'AD Russell', 'IK Pathan',
       'UT Yadav', 'BJ Hodge', 'SC Ganguly', 'WP Saha', 'OA Shah',
       'LR Shukla', 'RS Gavaskar', 'SE Bond', 'M Kartik', 'I Sharma',
       'SP Goswami', 'KS Williamson', 'PK Garg', 'JO Holder',
       'YV Takawale', 'AM Rahane', 'ST Jayasuriya', 'AM Nayar',
       'Harbhajan Singh', 'DS Kulkarni', 'C Nanda', 'SL Malinga',
       'V Sehwag', 'GJ Bailey', 'BR Dunk', 'CJ Anderson', 'AT Rayudu',
       'AP Tare', 'CM Gautam', 'Z Khan', 'LS Livingstone', 'SPD Smith',
       'AJ Turner', 'S Badrinath', 'RA Jadeja', 'KMDN Kulasekara',
       'R Ashwin', 'YBK Jaiswal', 'D Padikkal', 'SO Hetmyer', 'R Parag',
       'KL Rahul', 'CH Gayle', 'MA Agarwal', 'AJ Finch', 'AR Patel',
       'AJ Tye', 'BB Sran', 'MM Sharma', 'AA Bilakhia', 'TL Suman',
       'A Symonds', 'CA Lynn', 'SR Watson', 'BA Stokes', 'RD Gaikwad',
       'DP Conway', 'S Dube', 'P Kumar', 'JH Kallis', 'KP Pietersen',
       'R Dravid', 'R Bishnoi', 'R Vinay Kumar', 'DW Steyn', 'A Kumble',
       'Shakib Al Hasan', 'JD Ryder', 'GC Smith', 'AA Jhunjhunwala',
       'M Manhas', 'SB Wagh', 'R Sharma', 'RA Tripathi', 'RR Rossouw',
       'MA Starc', 'VR Aaron', 'AB Dinda', 'KS Bharat', 'JM Bairstow',
       'V Shankar', 'Mohammad Nabi', 'Abdul Samad', 'Rashid Khan',
       'Sandeep Sharma', 'B Kumar', 'D Brevis', 'Naman Dhir',
       'R Shepherd', 'JR Philippe', 'Navdeep Saini', 'YS Chahal',
       'TM Dilshan', 'A Mishra', 'MF Maharoof', 'VY Mahesh', 'PJ Sangwan',
       'Shubman Gill', 'B Sai Sudharsan', 'R Tewatia', 'M Vijay',
       'SE Marsh', 'R Dhawan', 'MG Johnson', 'Anureet Singh', 'SM Curran',
       'DJ Hussey', 'ML Hayden', 'A Flintoff', 'JDP Oram',
       'Joginder Sharma', 'T Thushara', 'Gurkeerat Singh', 'PR Shah',
       'RR Raje', 'JEC Franklin', 'IR Jaggi', 'B Chipli', 'KD Karthik',
       'JP Faulkner', 'MJ Lumb', 'FY Fazal', 'AC Voges', 'AS Raut',
       'AP Dole', 'LMP Simmons', 'MEK Hussey', 'Dhruv Jurel',
       'Rahmanullah Gurbaz', 'N Jagadeesan', 'VR Iyer', 'RK Singh',
       'SN Thakur', 'Karanveer Singh', 'PP Shaw', 'MP Stoinis',
       'Lalit Yadav', 'PC Valthaty', 'Bipul Sharma', 'RJ Harris',
       'BR Sharath', 'DG Nalkande', 'SH Johnson', 'Noor Ahmad',
       'LJ Wright', 'EJG Morgan', 'STR Binny', 'DR Sams', 'K Rabada',
       'LA Carseldine', 'LPC Silva', 'H Das', 'DNT Zoysa', 'KV Sharma',
       'AB Barath', 'RS Sodhi', 'RN ten Doeschate', 'MM Ali', 'DB Das',
       'R Bhatia', 'SMSM Senanayake', 'Azmatullah Omarzai',
       'M Shahrukh Khan', 'KK Ahmed', 'Shivam Mavi', 'Kuldeep Yadav',
       'J Suchith', 'R Ravindra', 'DJ Mitchell', 'R Sai Kishore',
       'A Ashish Reddy', 'DJG Sammy', 'GH Vihari', 'SB Dubey',
       'KK Cooper', 'VS Malik', 'DJM Short', 'M Kaif', 'Younis Khan',
       'Kamran Akmal', 'M Rawat', 'D Salunkhe', 'Pankaj Singh',
       'GHS Garton', 'MD Mishra', 'SP Jackson', 'AC Blizzard', 'MM Patel',
       'DL Chahar', 'MA Wood', 'Imran Tahir', 'SN Khan', 'D Wiese',
       'Abhishek Sharma', 'N Pooran', 'AK Markram', 'Umran Malik',
       'SE Rutherford', 'CA Ingram', 'AF Milne', 'S Badree', 'S Aravind',
       'E Lewis', 'GD Phillips', 'Anuj Rawat', 'DJ Willey',
       'PWH de Silva', 'RD Chahar', 'JJ Bumrah', 'TA Boult', 'S Sohal',
       'CL White', 'MJ McClenaghan', 'Atharva Taide', 'MW Short',
       'P Simran Singh', 'Harpreet Singh', 'JM Sharma', 'Harpreet Brar',
       'NT Ellis', 'MN Samuels', 'MR Marsh', 'RK Bhui', 'T Stubbs',
       'Abishek Porel', 'MJ Clarke', 'MK Lomror', 'K Gowtham',
       'JC Archer', 'JJ Roy', 'CV Varun', 'SM Katich', 'S Anirudha',
       'A Nehra', 'SW Billings', 'MC Henriques', 'DJ Hooda',
       'BCJ Cutting', 'JDS Neesham', 'R Shukla', 'Mohammed Shami',
       'Rasikh Salam', 'PBB Rajapaksa', 'Arshdeep Singh', 'S Kaul',
       'AB Agarkar', 'CK Langeveldt', 'AUK Pathan', 'CA Pujara',
       'JJ van der Wath', 'DL Vettori', 'Anmolpreet Singh', 'H Klaasen',
       'Sanvir Singh', 'M Jansen', 'M Markande', 'Fazalhaq Farooqi',
       'M Morkel', 'RS Bopara', 'Parvez Rasool', 'Shashank Singh',
       'SA Asnodkar', 'SK Warne', 'Sohail Tanvir', 'C Munro',
       'KW Richardson', 'AA Kulkarni', 'A Badoni', 'VG Arora', 'TM Head',
       'Nithish Kumar Reddy', 'S Chanderpaul', 'MV Boucher', 'B Akhil',
       'S Gopal', 'Kartik Tyagi', 'S Nadeem', 'R Sanjay Yadav',
       'Ramandeep Singh', 'J Botha', 'AL Menaria', 'I Udana',
       'KB Arun Karthik', 'A Mithun', 'PJ Cummins', 'RR Sarwan',
       'WG Jacks', 'Saurav Chauhan', 'Vijaykumar Vyshak', 'B Indrajith',
       'Sachin Baby', 'PV Tambe', 'SK Trivedi', 'K Goel', 'JR Hopes',
       'HM Amla', 'MD Shanaka', 'A Manohar', 'VRV Singh', 'U Kaul',
       'TG Southee', 'N Saini', 'SD Chitnis', 'B Lee', 'Iqbal Abdulla',
       'L Balaji', 'J Fraser-McGurk', 'SD Hope', 'TM Srivastava',
       'MC Juneja', 'T Kohler-Cadmore', 'R Powell', 'J Theron',
       'RJ Peterson', 'TD Paine', 'M Muralitharan', 'A Nortje',
       'Mukesh Kumar', 'AG Paunikar', 'RE van der Merwe', 'NS Naik',
       'VVS Laxman', 'Jaskaran Singh', 'LA Pomersbach', 'WA Mota',
       'RR Powar', 'MS Wade', 'AC Thomas', 'W Jaffer', 'RT Ponting',
       'T Shamsi', 'Abdul Basith', 'SD Lad', 'AS Joseph', 'KR Mayers',
       'JD Unadkat', 'Ravi Bishnoi', 'Avesh Khan', 'Y Nagar', 'M Ashwin',
       'RP Meredith', 'Sumit Kumar', 'FA Allen', 'TS Mills', 'AD Hales',
       'G Coetzee', 'SZ Mulani', 'MJ Santner', 'D Pretorius',
       'KC Cariappa', 'Mohammad Hafeez', 'KP Appanna', 'RJ Quiney',
       'PD Salt', 'RE Levi', 'SS Prabhudessai', 'WD Parnell',
       'Mohammad Asif', 'GD McGrath', 'M Klinger', 'DR Shorey', 'A Zampa',
       'DH Yagnik', 'CR Brathwaite', 'NLTC Perera', 'B Stanlake',
       'A Choudhary', 'DJ Harris', 'PA Reddy', 'J Arunkumar',
       'Misbah-ul-Haq', 'DT Patil', 'Abdur Razzak', 'D Ferreira',
       'SM Harwood', 'MS Gony', 'LE Plunkett', 'Harmeet Singh', 'P Awana',
       'AB McDonald', 'KS Sharma', 'Mohsin Khan', 'S Sriram', 'T Banton',
       'KL Nagarkoti', 'M Prasidh Krishna', 'LH Ferguson', 'PN Mankad',
       'WPUJC Vaas', 'Shoaib Ahmed', 'Tanush Kotian', 'KA Maharaj',
       'A Tomar', 'TR Birt', 'AD Mascarenhas', 'B Sumanth',
       'MG Bracewell', 'CRD Fernando', 'GC Viljoen', 'TL Seifert',
       'L Wood', 'B Laughlin', 'SP Fleming', 'S Vidyut', 'M Ntini',
       'TK Curran', 'AS Rajpoot', 'Mujeeb Ur Rahman', 'BJ Rohrer',
       'Mustafizur Rahman', 'UT Khawaja', 'Arjun Tendulkar',
       'Ashutosh Sharma', 'Sikandar Raza', 'AP Majumdar', 'CJ Ferguson',
       'AG Murtaza', 'P Chopra', 'P Dogra', 'A Uniyal', 'Yudhvir Singh',
       'P Parameswaran', 'JR Hazlewood', 'Ankit Sharma', 'Kumar Kushagra',
       'JA Richardson', 'J Syed Mohammad', 'R Rampaul', 'S Randiv',
       'DE Bollinger', 'BMAJ Mendis', 'AS Roy', 'Harshit Rana',
       'Anirudh Singh', 'AD Nath', 'Basil Thampi', 'Mukesh Choudhary',
       'SS Cottrell', 'SB Bangar', 'AS Yadav', 'AN Ahmed', 'F Behardien',
       'T Natarajan', 'RV Gomez', 'S Sreesanth', 'PVD Chameera',
       'IC Pandey', 'JE Root', 'KM Asif', 'L Ronchi', 'SM Pollock',
       'MA Khote', 'S Ladda', 'DP Nannes', 'BB Samantray',
       'Aman Hakim Khan', 'JM Kemp', 'RA Bawa', 'OF Smith', 'YV Dhull',
       'HC Brook', 'DJ Jacobs', 'MJ Guptill', 'Swapnil Singh',
       'Sunny Gupta', 'C Sakariya', 'Arshad Khan', 'Naveen-ul-Haq',
       'PD Collingwood', 'CK Kapugedera', 'SJ Srivastava', 'S Lamichhane',
       'NL McCullum', 'JE Taylor', 'Y Gnaneswara Rao', 'AA Noffke',
       'SB Joshi', 'AU Rashid', 'VS Yeligati', 'DS Lehmann', 'AA Chavan',
       'GB Hogg', 'Akash Deep', 'RV Patel', 'AT Carey', 'HR Shokeen',
       'UA Birla', 'K Upadhyay', 'NM Coulter-Nile', 'KMA Paul',
       'A Raghuvanshi', 'DJ Thornely', 'SA Abbott', 'BA Bhatt',
       'BAW Mendis', 'A Mukund', 'Sunny Singh', 'Yashpal Singh',
       'SS Shaikh', 'R Ninan', 'Mayank Dagar', 'RJW Topley', 'S Narwal',
       'SW Tait', 'Sameer Rizvi', 'HE van der Dussen', 'KR Sen',
       'Salman Butt', 'Umar Gul', 'TU Deshpande', 'MN van Wyk',
       'DAJ Bracewell', 'A Kamboj', 'Shoaib Malik', 'S Kaushik',
       'T Henderson', 'Kamran Khan', 'KAJ Roach', 'Virat Singh',
       'A Chopra', 'Simarjeet Singh', 'M Theekshana', 'L Ablish',
       'P Dubey', 'S Tyagi', 'AN Ghosh', 'P Ray Barman', 'BE Hendricks',
       'TP Sudhindra', 'C Ganapathy', 'DJ Muthuswami'], dtype=object)